### PR TITLE
Project discontinuation rough draft

### PR DESCRIPTION
**Pull request by markcmiller86**
* Wasn't sure how to categorize this...mainly because it isn't done and I wanna get feedback where its headed
* In its present form, might be best as a CC...but I've yet to find some good resources to link to especially for our special case(s)
* Am looking for others to read (for content and direction, not style) and suggest improvements or options
* AFAIK...I branched from `preview` branch so I think I did this right.

### CODE REVIEW

**Comment by bernhold** [comment]
Mark, you should always work from master.  In the new workflow, preview is maintained automatically (hence the bot you encountered).

**Comment by rinkug** [comment]
@markcmiller86 Is there a follow-on PR for this?

**Comment by markcmiller86** [comment]
> @markcmiller86 Is there a follow-on PR for this?

Yes. #601

**Comment by bartlettroscoe** [comment]
@markcmiller86, is this already merged to 'master'?  What is the status of this?  Can you change the merge target from 'preview' to 'master'?

**Comment by bartlettroscoe** [comment]
@markcmiller86 says he will not pursue this further.  So I will remove from the board.

**Pull request closed without merging**
