### PR TITLE
Removing categories metadata

### PR DESCRIPTION
**Pull request by karbarz**
Removed category metadata from CC example listed on EB Docs site.

### CODE REVIEW

**Comment by karbarz** [comment]
This is the second PR regarding issue #712. This issue should now be completed. 

The category metadata tag has been removed from all examples listed on the EB docs pages. 
@rinkug @curfman

**Comment by rinkug** [comment]
To discuss: while we are updating these files, we should remove other metadata that is deprecated as well.

**Comment by bartlettroscoe** [comment]
I added this to the BSSW Internal board to make this more visible.

**Comment by rinkug** [comment]
I have removed the deprecated tags and added the 4 tags to the files mentioned as examples

**Comment by rinkug** [comment]
> While we are updating these files, we should remove other metadata that is deprecated as well.
> @kasia, For all the files that serve as examples, lets have only the 4 current metadata in it:
> 
> * Please do the following if any of the 4 metadata is absent in the file
>   ** Publish: should be present, dont change this.
>   ** Pinned: If not present, please add "Pinned: no"
>   ** Topics: should be present, dont change this.
>   ** RSS update: this may not be present in some file. Please add this tag and the date should be the original publication date in the article.
> * Could you please remove "Tags", "Level", "Prerequisites" or anything else from the files?
> 
> Also note that once the files are modified, please check each of the files on the preview website and ensure that the edits did not break anything.

I have removed the deprecated tags and added the 4 tags to the files mentioned as examples.

**Review by rinkug — APPROVED** [review]

**Review by rinkug — APPROVED** [review]

**Pull request merged**
