### PR TITLE
Add big data child topic

### PR DESCRIPTION
**Pull request by markcmiller86**
# Description

EB Member: @bernhold 

Resolves portion of #1377 

This is a minor revision of metadata blocks to appropriate articles.

I took a first whack at this searching for all `.md` files that mention `big data`, `analytics`, or `data science`. Now that I think about it, I should have done from google because my workflow won't catch terms if line break appears between the words.

That said, I wanna make sure I am on the right track regarding following...
* Handling events and articles
* adding `performance` topic if it wasn't previously there before adding `big data`
* Doing very cursory read of article to assess whether it is very relevant to big data.

### CODE REVIEW

**Review by bernhold — COMMENTED** [review]
Hi @markcmiller86 I would say that just because an article mentions (big) data doesn't necessarily mean that there is any substantive content on the topic provided by that resource.

Of these articles, I would say that the Jupyter and HDF5 webinars are probably the best candidates for the big data topic.  I would not apply it to the others.

**Comment by bernhold** [comment]
Also, for everyone's information the `category` metadata element is not used.  Only the topics are used.  The categories are derived from the topics.

**Comment by markcmiller86** [comment]
@bernhold ok, I've undid the draft changes I've made to the other docs here.

Short of manually going through all files to manually examine them at this point (I was using some grep operations above to narrow scope -- I figured terms like `big data`, `analytics` or `data science` would almost certainly have to appear in any article dealing with that topic in a substantive way so if those terms do not exist in an article, it likely is not a candidate to begin with), do you have any other recommendations for completing this task?

**Comment by bernhold** [comment]
@markcmiller86  that seems reasonable to me.  I based my cloud computing changes on similar searches of the site.  I think it is good enough to go on with.

**Review by bernhold — APPROVED** [review]

**Pull request merged**
