### PR TITLE
Draft article for "rate your project" session held at ECP 2020

### PR DESCRIPTION
**Pull request by jarrah42**
PR for issue #469

### CODE REVIEW

**Comment by rinkug** [comment]
@jarrah42 Is this blog article done from your side and just waiting to be reviewed?

**Comment by rinkug** [comment]
@jarrah42 This is a good article. A couple of points after review.
1. Would it be useful to mention number of projects who took the survey.

2. "Better Development" categories scored significantly higher than the other categories. But what categories in better development were teams stronger in? Was there any particular area that majority of scientific team excelled in? 

3. Same questions for areas of weakness (in greatest to least order) were: Onboarding, Software Design, Reproducibility, Deployment, Requirements Analysis, and Due Diligence...

4. We need 1-2 short paragraphs on what the teams can do to improve their scores....

**Comment by jarrah42** [comment]
Since this wasn't a scientific experiment, I hesitate to try to infer too much from the results. I think drilling into the data in this way would give a misleading impression that the results could be meaningful. I'll add something about improving though...

**Comment by rinkug** [comment]
Ask Greg to update article with the web version of the poster that eh is working on.

**Review by rinkug — APPROVED** [review]

**Pull request merged**
