### PR TITLE
Draft Blog Post

### PR DESCRIPTION
**Pull request by whart222**
Hello BSSw Team,

One of the deliverables for my BSSw Fellowship is a blog post on the bssw.io site.  This is a draft of that blog post that is ready for editorial review.

Note that further details regarding this deep dive are included in two separate blog posts that I published recently.

--Bill

### CODE REVIEW

**Comment by bernhold** [comment]
Thanks @whart222, I'll put this in our publication queue and I'll let you know when I start working on it.

**Comment by bernhold** [comment]
Hi @whart222 , as you've probably noticed, I've made an initial edit pass through your blog article.  I made some changes to your text for clarity.  I think there are also several ways this article could be improved.

1. I think most in our community do not know what SBOM is or why they should care.  I think it would be a good idea if the article provided some additional background/motivational information.
2. Because Fortran is still an important programming language in our community, it would be nice if you could find *something* to say about SBOMs for Fortran codes.  Maybe the the answer is that no one seems to be working on this, but if that's so, maybe you can at least say that rather than leaving out Fortran entirely?  Although maybe the cmake-sbom tool, or some evolution of it, could potentially be used with Fortran codes too?

I've planted some text in the article to try to provide the seeds of addressing my points above (look for the bold text), but I'd appreciate it if you could respond in your own way.

Also, I have some concerns about the image you proposed for the hero.  First of all, it is not a great match for our guidelines for hero images, but I think it is potentially useful to help readers understand what goes into an SBOM.  So I've moved it into the body.  But also, the image comes from a company's website.  Normally, we use only images that we host in our own repository, and I'm checking whether there are any technical concerns about referring to another site. (Besides the obvious possibility that they'll move or remove the image on us, without notice.)  But also, do you have permission from the company to use it?  Legally, maybe it is okay if we reference it instead of taking a copy and hosting it ourselves, but I'm not sure we would want to go there.  I think our designers could create an equivalent diagram without too much trouble, but I'm not sure we have time to do it.

I'm hoping that you will be able to address these matters quickly and easily.  Our target for publication is Tuesday 28 May, and with the Monday holiday, I know that's not a lot of time.  Let me know if you think it will be a problem.

Thanks!

**Comment by whart222** [comment]
Hi, Dave.  I'm not sure what to recommend w.r.t. the image.  I'm comfortable using a different image, but I don't know that there is a canonical "free" image to use here.

**Comment by bernhold** [comment]
Let me see if our designers could quickly do something for us.  It would like better anyway -- color and style more consistent with our preferences.

**Comment by whart222** [comment]
I took a stab at revising the text you bolded.  I left the second sentence bolded, as it captures a key motivation for members of the scientific software community.

Let me know if you have other questions or concerns.

**Comment by bernhold** [comment]
Hi @whart222, I was wondering what your status is?  Do you feel that you've addressed all of my comments/requests?

I think we'll need to delay publication a bit regardless.  We still need an editorial pass, which probably can't happen today, and our designers are working on a replacement for the SBOM graphic, which I haven't received yet.

**Comment by bernhold** [comment]
@whart222 please confirm that you're done with the changes you wanted to make.  I know you've been hands-off for a while now, but a direct confirmation would be helpful.  Thanks

**Comment by whart222** [comment]
Yes, I think so.  Do you have any questions or concerns about my edits?

**Comment by bernhold** [comment]
Thanks.  It will be a couple of days before I can take a careful look at it, but initially, they look good.

**Comment by bernhold** [comment]
Accidentally merged prematurely.  Reverted by #2114 and recreated in #2115.

**Pull request merged**
