### PR TITLE
Add april developer survey post

### PR DESCRIPTION
**Pull request by vsoch**
# Description

Author: @vsoch 
EB Member: @markcmiller86 

This is a draft of the developer survey post for April. Let me know what I need to do - this checklist is a little overwhelming! 

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [ ] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

## PR checklist for (internal) files not displayed on bssw.io site

*Click "Write" above and remove comment markers to see below checklist items*

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by markcmiller86** [comment]
@vsoch...awesome! Thanks so much for drafting this! We'll have a review of it this week and follow up.

**Comment by markcmiller86** [comment]
@bernhold I am in processing of submitting a few stacked PRs against this one. Should have something closer to copy-ready sometime next week. I think actual target publication date is up to you. I just wanted to get this in the queue so its there when you need it.

**Comment by markcmiller86** [comment]
> This is a draft of the developer survey post for April. Let me know what I need to do - this checklist is a little overwhelming!

@vsoch BTW...you don't need to worry about the checklist items. Those are for us mainly.

**Comment by markcmiller86** [comment]
@bernhold given that I can do stack PRs here, most of the prep. conversation about this is occuring here...

https://github.com/researchapps/betterscientificsoftware.github.io/pull/2

**Comment by bernhold** [comment]
Hi @vsoch I'm working on getting your blog post ready for publication.  I wasn't able to work directly in your PR, as we normally do.  Have you disabled write access for maintainers?  If so, would you be willing to re-enable it?  (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)  It will allow us to finalize things more easily and with less need to bother you.  You'll have an opportunity for a final review prior to publication. Thanks

**Comment by vsoch** [comment]
It’s an org account, so I’ll add you as a maintainer.

**Comment by vsoch** [comment]
Ok just gave you write access - once you accept via the email it should work I think! Let me know if you have any trouble.

**Comment by bernhold** [comment]
That worked.  Thanks!

Another question: is the hero image you've suggested something that you created or is it a stock graphic of some kind?  If so, what's the source?  Thanks

**Comment by vsoch** [comment]
It’s totally made by me with stable diffusion.

**Pull request merged**
