### PR TITLE
Agile Software Development Principles, Patterns, and Practices (#383)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Authors: Ross B.
EB member: Mark M.

Adds the curated content article for "Agile Software Development Principles, Patterns, and Practices" by Robert Martin approved in #383.

## ToDos:

* [x] Copy over skeleton and fill in the text
* [x] Determine desired format for references
* [x] Put in the references
* [x] Add book cover image to 'images' repo and provide link to that from this `*.md` file
* [ ] Get article reviewed and approved
* [ ] Merge this PR to 'master' and set 'Publish: preview' mode
* [ ] Address any issues on the 'preview' site with new commits to 'master'
* [ ] Set 'Publish: on' and commit to 'master'

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@markcmiller86, when you get some time, can you please review this?  You were listed as the EB board member in the originating issue #383.

**Review by markcmiller86 — APPROVED** [review]
Excellent review! One typo...add a comma after `This book,` in second sentance.

**Comment by bartlettroscoe** [comment]
> Excellent review! One typo...add a comma after This book, in second sentance.

Thanks @markcmiller86!  I added this in commit https://github.com/betterscientificsoftware/bssw.io/pull/580/commits/4ed6feb1ffed58a68e81305fdd85eb23aff88628.  I will go ahead and merge so we can see this on the 'preview' site to see how this looks.

**Comment by rinkug** [comment]
This has been published: https://bssw.io/items/digging-deeper-into-agile-software-development

**Pull request merged**
