### PR TITLE
Follow-on tweaks to PR template from PR #765 (#695)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @markcmiller86 

Addresses issue #695

Follow-on tweaks to address feedback for the PR template first merged in PR #765.

## PR checklist for (internal) files not displayed on bssw.io site

* [x] Set list of Reviewers (at least one).
* [x] Add to Project [BSSw Internal].
* [ ] View the modified `*.md` files as rendered in GitHub.
* [ ] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.
* [ ] Watch for PR check failures.
* [ ] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [ ] Ensure at least one reviewer signs off on the changes.
* [ ] Once reviewer has approved and PR check pass, then merge the PR.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Review by markcmiller86 — COMMENTED** [review]
Apologies but I guess I am confused. Except for the two *optional* items associated with citations/refs, is anything else on this checklist optional? If not, then do we really need to inform submitters they can strike out items they deem optional? If so, who has the power to decide if an item is trully optional? If the submitter has that power, then aren't we encouraging them to not follow the checklist?

**Comment by markcmiller86** [comment]
So, I hadn't read the doc material *before* the checklist and I honestly think that covers intended usage sufficiently that the after-note is not even necessary.

That said, I do think there is still an open question...do we expect authors/submitters to selectively skip various steps in the checklist? If not, then maybe don't suggest that in the notes.

I don't think its a big deal for now so will approve and we can chat more about when appropriate.

**Review by markcmiller86 — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
> That said, I do think there is still an open question...do we expect authors/submitters to selectively skip various steps in the checklist? If not, then maybe don't suggest that in the notes.

Based on this feedback, I think we should just remove that NOTE after the checklist and leave the instructions above that say you can strike out steps.  And I think there are steps that don't apply to every PR so it is better to strike out the checklist item than to just not check it or to check it when you did not do anything to satisfy the checklist item.   When you strike out a checklist item you are saying "I considered the checklist item and it does not apply in this case and I am not going to do it".

**Comment by bartlettroscoe** [comment]
I will go ahead and merge this.  We can make more tweaks in follow-up PRs (small PRs are no big deal).

**Pull request merged**
