### PR TITLE
Propose alternative WhatIsInclusivity

### LINKED ISSUE #1935: Empty what-is articles.
We need what-is articles for the following:

- [ ] * [Programming Languages](https://bssw.io/items?topic=programming-languages)
- [ ] * [High-Performance Computing (HPC)](https://bssw.io/items?topic=high-performance-computing-hpc)
- [ ] * [Cloud Computing](https://bssw.io/items?topic=cloud-computing)
- [ ] * [Big Data](https://bssw.io/items?topic=big-data)
- [x] * [Inclusivity](https://bssw.io/items?topic=inclusivity) (by @rinkug)
- [ ] * [Personal Productivity and Sustainability](https://bssw.io/items?topic=personal-productivity-and-sustainability)(@pagrubel) PR #1944

### PR DESCRIPTION
**Pull request by markcmiller86**
Partly resolves #1935

I am proposing an alternative WhatIsInclusivity statement here.

I wanted to try to combine the original draft with this but wound up feeling like the two are substantially different in focus.

### CODE REVIEW

**Comment by markcmiller86** [comment]
Ok, I worry `codespell` is giving false negatives here. I was stunned it turned up no misspellings because I am a horrible speller and typist. So, I would have expected `codespell` to flag some things. It did not.

Then, I used `aspell` on my machine locally `cat WhatIsInclusivity.md | aspell list | sort | uniq` and I see it finds `collaborte` which is not an English language word that I know of. So, why did `codespell` indicate it is ok?

**Comment by markcmiller86** [comment]
So, what *files* does the workflow actually run the tool on. All I see is this line where `codespell` is invoked...

https://github.com/betterscientificsoftware/bssw.io/actions/runs/7268281718/workflow?pr=1943#L27

**Comment by rinkug** [comment]
> I am proposing an alternative WhatIsInclusivity statement here.
> 
> I wanted to try to combine the original draft with this but wound up feeling like the two are substantially different in focus.

Thanks Mark. Please feel free to change it. Different perspective are welcome and I am happy to replace mine when yours is ready

**Comment by rinkug** [comment]
This could perhaps be a short article in itself :)

**Comment by markcmiller86** [comment]
@betterscientificsoftware/bssw-editorial-board I've also proposed a change to the topic description here as well.

**Comment by rinkug** [comment]
@markcmiller86 : is this still a replacement for my version of what-is (which is perfectly ok) or is this more of a short article?

**Comment by rinkug** [comment]
@markcmiller86 : Should I go ahead and merge this as a what-is article?

**Comment by markcmiller86** [comment]
> @markcmiller86 : Should I go ahead and merge this as a what-is article?

If you are fine with it, then yes please.

**Pull request merged**
