### PR TITLE
Create MaintainersDEIResourceHub

### LINKED ISSUE #1536: GitHub "All In for Maintainers" DEI Resource Hub
Author: @haikudeb 
EB @rinkug 
https://github.blog/2023-02-01-announcing-the-launch-of-the-all-in-for-maintainers-dei-resource-hub/

### PR DESCRIPTION
**Pull request by haikudeb**
CC for All In for Maintainers Resource Hub

# Description

EB Member: @rinkug 

Resolves #1536 

CC for August 2023 about DEI Resources for Maintainters written by @haikudeb 

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** @haikudeb  the BSSw.io editorial board member @rinkug  in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the #1536 in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member @rinkug .
* [x] ***[EB Mem]*** Assign this PR to the author of the PR @haikudeb .
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

## PR checklist for (internal) files not displayed on bssw.io site

*Click "Write" above and remove comment markers to see below checklist items*

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
> I put down Rinku, yes. At least I think I assigned it properly 

@haikudeb, the idea is that you make the EB member explicit by listing them in the **Description** section by replacing:

```
EB Member: @`<eb-member-id>`
```

with:

```
EB Member: @rinkug 
```

and fill in other `<input-field>` placeholders.   (GitHub PRs don't have a way to define extra fields so we have to do that manually.  GitHub only support "Assignees" and "Reviewers" but technically the EB member may not be a reviewer and there may be multiple assignees of which one may not be the EB member.  So we state it explicily.)

Also, the idea is that you would delete the instructions section and the lower section **PR checklist for (internal) files not displayed on bssw.io site** if the PR is for a bssw.io article.

How can we update the instructions to make this more clear?

**Comment by rinkug** [comment]
@haikudeb : this needs to focus on the DEI resource hub and not the annoucement itself.

**Comment by haikudeb** [comment]
I can make changes . I'm not exactly sure how do do that in the midst of the PR

**Comment by rinkug** [comment]
> I can make changes . I'm not exactly sure how do do that in the midst of the PR

Go to "files changed" and then edit the files in the PR...

**Comment by haikudeb** [comment]
I am not seeing any tabs, or drop downs or tables or labels that say "files changed" 
I've done a fairly solid explore and not finding "files changed"  
Where do I find it?

**Comment by haikudeb** [comment]
OK. I did find it. It's there if one views this message stream within GitHub

**Comment by haikudeb** [comment]
> @haikudeb : this needs to focus on the DEI resource hub and not the annoucement itself. Shall I make the changes or can you do it? We should aim to publish this soon. Happy to help!

The CC issue pointed to the "launch of the dei resource hub" website. Do want me to change the website to the All in for Maintainers one instead ?

**Comment by haikudeb** [comment]
What is the next step with this CC?

**Comment by rinkug** [comment]
I cannot edit this PR or post comments. I will close this PR and open a new one.

**Pull request closed without merging**
