### PR TITLE
Add LLNL HPC Tutorials event

### LINKED ISSUE #2102: Event Notice: Tutorials: LLNL HPC Software
By making a submission here, you agree to [[BSSw.io](http://bssw.io/) content licensing terms](https://github.com/betterscientificsoftware/bssw.io/blob/main/TERMS.md).

Enter details here by replacing *italicized text* with actual event information and without adding or removing lines.  You are encouraged to look at some [published events](https://bssw.io/events) in order to get a feel for how the requested information will appear on the site.

Questions can be directed to hpcic-tutorials@llnl.gov or https://github.com/kab163 or https://github.com/hauten

* **What:** *Tutorials: LLNL's HPC Software*

* **When:** *August 1, 2024 – August 29, 2024*

* **Where:** *Online*

* **Organizers:** *Lawrence Livermore National Lab's High Performance Computing Innovation Center*

* **Website:** *[URL for event web site](https://hpcic.llnl.gov/2024-hpc-tutorials)*

* **Summary:** *Learn how to use a modern, open-source HPC software stack! Throughout August, join our free tutorials on how to install and use several projects on AWS EC2 instances. No previous experience is necessary, and everyone is welcome.*

* **Description:** *Throughout August, LLNL's High Performance Computing Innovation Center will host free tutorials covering a wide range of HPC needs including package management, memory management, workflow management, portability, performance, visualization, math libraries, and more. Twelve software teams will walk you through installation, configuration, and getting started. Attendees will be provided with AWS instances so that they can follow along with the tutorials in real time. No previous experience necessary, and everyone is welcome. You can sign up for any/all of these tutorials. Visit the [event website](https://hpcic.llnl.gov/2024-hpc-tutorials) for the schedule and sign-up link.*

### PR DESCRIPTION
**Pull request by markcmiller86**
Resolves #2102 

This is a somewhat unusual event so its formatted a little differently. 

I hope that is ok.

### CODE REVIEW

**Comment by markcmiller86** [comment]
ping @hauten

**Comment by markcmiller86** [comment]
@betterscientificsoftware/bssw-editorial-board I believe this is ready for publication.

**Comment by hauten** [comment]
thanks @markcmiller86

**Comment by hauten** [comment]
Thanks again @markcmiller86. I'll save this link so next year I'll know how to format the event correctly.

**Pull request merged**
