### PR TITLE
Remove wikized variants

### LINKED ISSUE #779: Issues with wikize_refs.py and existing <base>-wikized.md files
@markcmiller86,

There appears to be some issues running the updated `wikized_refs.py` tool on the existing `<base>-wikized.md` files in the bssw.io repo, I am getting errors.  The files that I am trying to run this on are:

```
[rabartl@crf450 bssw.io (master)]$ find . -name "*-wikized.md" | grep -v ReferencesInMarkdown
./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart2-wikized.md
./Articles/Blog/Covid19WorkstationCleanliness-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart3-wikized.md
./Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md
```

I am getting error output like:

```
$ ./wikized_refs.py -i -w ./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
Some footnotes never appear in the references...
['24', '26', '27', '20', '21', '16', '33', '32', '31', '13', '35', '36', '12', '4', '8']
Some references never appear in a footnote...
['51', '48', '49', '46', '47', '44', '45', '42', '29', '40', '43', '0', '55', '53', '52', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '4'
```

The full error output from from all of the runs is given in the detailed output below.

<details>

<summary><b>Detailed error output</b> (Click to expand)</summary>

. 

```
$ for md_file in $(find . -name "*-wikized.md" | grep -v ReferencesInMarkdown) ; do echo ; echo ; echo $md_file ; echo ; ./utils/wikize_refs.py -i -w $md_file ; done


./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md

Some footnotes never appear in the references...
['24', '26', '27', '20', '21', '16', '33', '32', '31', '13', '35', '36', '12', '4', '8']
Some references never appear in a footnote...
['51', '48', '49', '46', '47', '44', '45', '42', '29', '40', '43', '0', '55', '53', '52', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '4'


./Articles/Blog/ApolloGuidanceComputerPart2-wikized.md

Some footnotes never appear in the references...
['11', '39', '27', '14', '48', '49', '33', '32', '22', '37', '36', '35', '52', '1', '16', '2', '17', '30', '38']
Some references never appear in a footnote...
['59', '58', '0', '55', '54', '57', '56', '53', '60', '61', '62', '65', '66', '67', '68']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '35'


./Articles/Blog/Covid19WorkstationCleanliness-wikized.md

Some footnotes never appear in the references...
['15', '14', '17', '16', '19', '37', '28', '36', '35', '34', '18']
Some references never appear in a footnote...
['48', '49', '46', '47', '44', '45', '42', '43', '40', '41', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 307, in build_main_content
    (ref_map[fn[0]][3],ref_map[fn[1]][3],ref_map[fn[2]][3]), mcl)
KeyError: '17'


./Articles/Blog/ApolloGuidanceComputerPart3-wikized.md

Some footnotes never appear in the references...
['4']
Some references never appear in a footnote...
['28']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 297, in build_main_content
    mcl = re.sub("<sup>\[%s\]</sup>"%fn, "<pus>[%d]</pus>"%ref_map[fn][3], mcl)
KeyError: '4'


./Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md

Some footnotes never appear in the references...
['8']
Some references never appear in a footnote...
['25', '26']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 307, in build_main_content
    (ref_map[fn[0]][3],ref_map[fn[1]][3],ref_map[fn[2]][3]), mcl)
KeyError: '8'
```

</details>

Any idea what the problem might be?

### PR DESCRIPTION
**Pull request by markcmiller86**
Resolves #779 

The set of files with `-wikized` (and to be removed/replaced with *just* the `.md` version) are...

```
./Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md
./Articles/Blog/Covid19WorkstationCleanliness-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart2-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart3-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
./Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md
```

However, only the first four are changed/fixed in this PR. The 5th entry above, `./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md` is fixed in #851 and the 6th item above is not hosted content. Further, we've decided we need to cull out of that file the *simple* example file we'll use as a template for demonstrating how `wikize_refs.py` operates.

To fix each of these files, I worked from the `-wikized.md` versions (which are the actual hosted content) and did these things...

* Ensured if any refs were *manually* added to the `-wikized.md` version, those refs were also manually reflected in the Author's original refs block
* Manually enumbered the refs from 1 to N in the Author's original refs block and uncommented that block
* Removed the intermediate and table blocks because `wikize_refs.py` will regenerate them
* Ensured bssw.io metadata was *ahead* of the Author's original refs block
* Ran `wikize_refs.py` on the file creating a `-wikized-wikized.md` version confirming no errors were produced by the tool
* Compared the resulting file to the original `-wikized.md` version and ensured no ref renumbering had occured
* Replaced the `.md` file with the `-wikized-wikized.md` file produced in the steps above
* Removed the `-wikized.md` file.

All of this represents changes to hosted content so I've added the preview flag here. That said, none of this is *new* content and so I don't have the normal checklist.

* [x] Set list of Reviewers (at least one).
* [x] Add to Project [BSSw Internal].
* [x] View the modified `*.md` files as rendered in GitHub.
* [ ] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.
* [x] Watch for PR check failures.
* [ ] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [ ] Ensure at least one reviewer signs off on the changes.
* [ ] Once reviewer has approved and PR check pass, then merge the PR.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by markcmiller86** [comment]
@bartlettroscoe, @rinkug and @bernhold, conflicts here too have bee resolved locally and this is ready to merge. But checks are failing.

**Comment by bernhold** [comment]
@markcmiller86 I fixed the conflicts by rebuilding preview from scratch.  Go ahead and merge.

**Review by bartlettroscoe — APPROVED** [review]
I did not look at every line of the change but I did check out this branch and verify that these files build in place correctly with no change:

```
[rabartl@s1049009 Blog (mcm86-remove-wikized-variants)]$ ./wikize_refs.py -i ApolloGuidanceComputerPart2.md 
"ApolloGuidanceComputerPart2.md" is up to date. No changes will be made.
[rabartl@s1049009 Blog (mcm86-remove-wikized-variants)]$ ./wikize_refs.py -i ApolloGuidanceComputerPart3.md 
"ApolloGuidanceComputerPart3.md" is up to date. No changes will be made.
[rabartl@s1049009 Blog (mcm86-remove-wikized-variants)]$ ./wikize_refs.py -i Covid19WorkstationCleanliness.md 
"Covid19WorkstationCleanliness.md" is up to date. No changes will be made.
[rabartl@s1049009 Blog (mcm86-remove-wikized-variants)]$ cd ../ShortArticles/
[rabartl@s1049009 ShortArticles (mcm86-remove-wikized-variants)]$ ../../utils/wikize_refs.py PullRequestSizeConsiderations.md 
"PullRequestSizeConsiderations.md" is up to date. No changes will be made.
```

However, I still find a couple more `*-wikized.md` files:

```
[rabartl@s1049009 bssw.io (mcm86-remove-wikized-variants)]$ find . -name "*-wikized.md"
./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
./Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md
./utils/build_tests/tests/wikize_refs_no_args_pass/ReferencesInMarkdownHybridApproach-wikized.md
```

And that file still fails to build:

```
 ./wikize_refs.py -i ApolloGuidanceComputerPart1.md 
Some footnotes never appear in the references...
['0', '4']
Correct above issues and re-try...
```

When will the file `ApolloGuidanceComputerPart1-wikized.md` get removed and have `ApolloGuidanceComputerPart1.md` fixed?  Is that addressed another PR?

But that is no reason not to merge this PR.

**Comment by bartlettroscoe** [comment]
Is this ready to merge?  Can I click "Merge pull request"?

**Comment by markcmiller86** [comment]
> When will the file `ApolloGuidanceComputerPart1-wikized.md` get removed and have `ApolloGuidanceComputerPart1.md` fixed? Is that addressed another PR?

Yes, that was in #851.

Regarding the other instances of `-wikized.md` files you mention...

* `./Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md`
* `./utils/build_tests/tests/wikize_refs_no_args_pass/ReferencesInMarkdownHybridApproach-wikized.md`

The first of these was part of *internal* documentation about how this works (so not published on bssw.io) and I needed a way to a) write about how the markdown is supposed to be constructed including demonstrating actual markdown examples and then b) produce the result of running `wikize_refs.py` on it to show how it looks.

But, I think we've decided that we actually need examples (e.g. templates) for all document types here and one of those examples will be an article with references/citations. That is #857. When that is completed, I think we'll just delete these cases then, ok?

**Comment by markcmiller86** [comment]
BTW...having that *internal* documentation file `ReferencesInMarkdownHybridApproach-wikized.md` in the `Articles/Blog` folder is probably also bad form. Nonetheless, I say leave it until #857 is completed. I'll add a note to #857 to delete this file then.

**Comment by markcmiller86** [comment]
> Nonetheless, I say leave it until #857 is completed. I'll add a note to #857 to delete this file then.

On second thought, there are several files related to *documenting* how references work (screen capture from GitHub search below)...

Screen Shot 2021-06-19 at 11 56 18 AM

The only one of these with stuff we should keep is... `ReferencesInMarkdownHybridApproach.md`. That file was actually performing *multiple* functions. One is documenting how authors should compose their markdown to make citations work. Another is documenting how `wikize_refs.py` tool actually works and does its job. Another is an actual *demo* of it working on some markdown and the wikized result. #857 is aimed only at the third of these...a template demonstrating how to properly compose markdown with citations and the wikized result.

So, instead of wholly *deleting* `RefernecesInMarkdownHybridApproach.md`. We should move the majority of it to become part of our internal docs (for authors).

**Pull request merged**
