### PR TITLE
Rebrand whatis inclusivity doc

### LINKED ISSUE #2001: Rebrand origin WhatIs for Inclusivity as blog and condense for WhatIs
By making a submission here, you agree to [BSSw.io content licensing terms](https://github.com/betterscientificsoftware/bssw.io/blob/main/TERMS.md).

You are welcome to submit an *idea* for a blog article or a completed article.

After your submission is received, it will be reviewed by the BSSw.io editorial staff and we will be in touch with you.

### PR DESCRIPTION
**Pull request by markcmiller86**
# Description

* Moves original `WhatIs/WhatIsInclusivity.md` to `Blog/2024-01-WhatIsInclusivity.md`
* Slight revisions to above
* Creates condensed version of above for `WhatIs/WhatIsInclusivity.md`

EB Member: @`<eb-member-id>`

Resolves #2001 

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bernhold** [comment]
Removing `preview` label until conflict is resolved.

**Comment by rinkug** [comment]
@markcmiller86 
Could you help with the following?

- [ ] - Resolve conflict
- [ ] - Add track to blog
- [ ] - Modify dates for both articles.
- [ ] 

@davidbernholdt 

- [ ] - What other things are needed from the blog perspective?  The title needs to be changed to H1, but anything else?
- [ ] - Should we highlight the content but this time as a blog in June timeframe in the digest? Either way, are you ok with us publishing the blog now?

**Comment by markcmiller86** [comment]
@rinkug and @bernhold I believe I have taken care of all issues mentioned either here on GitHub or in email.

I do not think a hero image is needed but if anyone else disagrees, here is one image I liked (but not all scientists wear white coats and in spite of all the diversity it shows, it is missing a representation of the disabled community.

image

**Comment by markcmiller86** [comment]
Following the check-list, I guess I need one reviewer at least to approve also.

**Comment by rinkug** [comment]
The blog is good. Changing date of blog to today's date and merging.
The cc is a repetition of the blog. Perhaps not a good idea to copy blog sentences in cc in verbatim. I can publish it but take a look into changing it later if that is ok.

I like the hero image. Agree about white coat comments etc. but overall its ok.

**Comment by bernhold** [comment]
@rinkug hang on!  If we're going to highlight in late June, better to delay the merge until then!

**Comment by bernhold** [comment]
Converted to draft to make it hard to merge "inadvertently"

**Comment by rinkug** [comment]
@markcmiller86 : Can I take over what-is article and change it to make it different than blog? (you can do it too-- but you have spent a lot of time on this so hate to ask you for more)

**Comment by rinkug** [comment]
Created a new image. Too colorful??  Not sure if it will fit in our rectangular box.
inclusivity

**Comment by markcmiller86** [comment]
> @markcmiller86 : Can I take over what-is article and change it to make it different than blog? (you can do it too-- but you have spent a lot of time on this so hate to ask you for more)

Yes...for sure. Please do. :heart:

**Comment by rinkug** [comment]
I am done with the what-is article. It can be published along with the blog since its tied to the same PR.

**Pull request merged**
