### PR TITLE
Event for ECP BOF Days

### PR DESCRIPTION
**Pull request by karbarz**
Creating .md file for BOF event.
In response to issue #719 
@curfman @rinkug

### CODE REVIEW

**Comment by rinkug** [comment]
1. No abbreviations in title
2. Remove "in conjuction with ECP annual meeting"
3. Expand abbreviations in body of article

**Comment by rinkug** [comment]
Also, please assign every event to the Content Development project board, put it in the right column, put the right label (event) as well.

**Comment by karbarz** [comment]
Requested updates made to article.
PR assigned to content board, in progress, and content tag added.

**Review by rinkug — APPROVED** [review]

**Review by rinkug — APPROVED** [review]

**Comment by rinkug** [comment]
@karbarz : Please check my recent edits and comment if approved

**Review by karbarz — COMMENTED** [review]
Corrected topic tags, made small grammar changes. 
All other changes look good.

**Pull request merged**
