### PR TITLE
Some revisions

### PR DESCRIPTION
**Pull request by markcmiller86**
These are suggestions for the how-to-contribute based on PR #1622

### CODE REVIEW

**Comment by rinkug** [comment]
I think we may have to retain some parts of the original text. While I understand everything you wrote, it may be too concise for the readers, especially the new ones.

**Comment by markcmiller86** [comment]
> @markcmiller86 I think we may have to retain some parts of the original text. While I understand everything you wrote, it may be too concise for the readers, especially the new ones.

Well, I guess I disagree...there was too much text there already and I felt it was conflating multiple concepts. Can we get some other @betterscientificsoftware/bssw-editorial-board team members to weigh in on it.

**Comment by rinkug** [comment]
@bernhold or @curfman  : Can you perhaps make a final pass on this?

**Review by bernhold — APPROVED** [review]
LGTM

**Pull request merged**
