### PR TITLE
Reformat articles for blog and add tracks

### LINKED ISSUE #1558: Adding track meta to all relevant articles
Related to #699.

Context: Blogs, original articles, howtos, what-is will now be distinguished using "tracks" and all these articles will be available under https://bssw.io/blog_posts. To achieve this, we need to add the "track" metadata in these articles. Since we are touching all these articles, we may as well remove old obsolete metadata.

- **We need to add new *Track* metadata to everything in [Articles directory]**(https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles)
    Track: Deep Dive/How To/Community/Experience/Bright Spots

- **What meta should each file ideally have?** 
   Ideally each file should have the following metadata as listed in the [BSSw.io Editorial Guide](https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html): 
    Publish: yes
    Pinned: no
    RSS Update: 2023-01-11
    Topics: projects and organizations
    Track: 

  **We dont know how RSS feed behaved, so dont add RSS update if a file does not already have that.**

- **We need to remove old metadata**
   Please remove anything that is obsolete other than what is mentioned above.

- **Do articles need to move between folders?**
  Yes eventually, but lets leave that aside for now.

### LINKED ISSUE #1877: Need content to replace old i-p.o HowTo articles
**[UPDATE by Rinku on Dec 12 2023] Team members have been assigned what articles they are responsible for  and its being tracked in this [excel tracking file](https://docs.google.com/spreadsheets/d/1DnR7EJ4RScRrnekxz4RQ8F9GBhy8BhvODiPq3JqPagU/edit#gid=842716675).**

A number of BSSw articles link to HowTo (and related) content that was hosted on the old ideas-productivity.org Wordpress site, which is no longer available since we put the Jekyll site into production.  We need to

1) Republish that material on BSSw
2) Change the BSSw articles to point to the new versions

As of 13 Oct, the following BSSw.io articles needed attention:

BSSw URL | Old i-p.o URL
-----------|----------------
https://bssw.io/items/what-is-software-configuration-673277bd-6df9-474a-86c5-7e9ee40d784e | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-ConfigurationWhatIsSoftwareConfiguration-V0.2.pdf
https://bssw.io/items/how-to-write-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationHowToWriteGoodDocumentation-V0.1.pdf
https://bssw.io/items/what-is-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationWhatIsGoodDocumentation-V0.1.pdf
https://bssw.io/items/how-to-enable-performance-portability-for-cse-applications | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceHowToEnablePerformancePortability-V0.2.pdf
https://bssw.io/items/what-is-performance-portability-for-cse-applications-eccf9c55-c76a-42cc-81ec-a0d288a3eb0a | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceWhatIsPerformancePortability-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/what-is-cse-software-testing | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatAreSoftwareTestingPractices-V0.2.pdf
https://bssw.io/items/what-is-revision-control | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-VCWhatIsVersionControl-V0.1.pdf
https://bssw.io/items/how-to-configure-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-ConfigurationHowToConfigureSoftware-V0.2.pdf
https://bssw.io/items/what-are-interoperable-software-libraries-introducing-the-xsdk | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-InteroperabilityWhatAreInteroperableSoftwareLibraries-V0.2.pdf
https://bssw.io/items/how-to-do-version-control-with-git-in-your-cse-project | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-VCHowToVersionControlwithGit-V0.2.pdf

### PR DESCRIPTION
**Pull request by markcmiller86**
Resolves #1558 
Resolves #1877 and ?

So, this is a tad more involved than on first glance.

* Do we remove the "How To" branding of the article? Effects titling
* What is/was the original publication date of the article?
* Does the article have a *companion* curated content that pointed at the old IDEAS classic site? If so, remove it
* Are there bad links in the article? If so, are they fixable?
* What do we do with links to other HowTo or WhatIs articles?
* Some articles have *notes to self*. They should be removed.
* Does the article use [here](https://www.google.com) a lot to link to other articles instead of providing more descriptive text?
* Does the DOE auspices need to remain? I think so but lets be sure.

I plan to add all my other articles here too so putting this in DRAFT mode until done.

### CODE REVIEW

**Comment by rinkug** [comment]
> * Do we remove the "How To" branding of the article? Effects titling
You mean the "howto" logo? Just delete it.

> * What is/was the original publication date of the article?
Everything is atleast 4 years old. Give it a date of Aug 15, 2019

> * Does the article have a _companion_ curated content that pointed at the old IDEAS classic site? If so, remove it
What do you mean?

> * Are there bad links in the article? If so, are they fixable?
I am deleting link or updating them.

> * What do we do with links to other HowTo or WhatIs articles?
Most of the will be in the same how-to folder, so we will have to update them.

> * Some articles have _notes to self_. They should be removed.
Yes

> * Does the article use [here](https://www.google.com) a lot to link to other articles instead of providing more descriptive text?
Some articles do. Edit articles as you can fit. 

> * Does the DOE admonishment need to remain? I think so but lets be sure.

The mention about funding? You can remove it. Everything on this site is funded through DOE anyways IMHO.

> I plan to add all my other articles here too so putting this in DRAFT mode until done.

**Comment by markcmiller86** [comment]
> * Does the article have a _companion_ curated content that pointed at the old IDEAS classic site? If so, remove it
>   What do you mean?

What I mean is...there are CC articles that are effectively *duplicates* of this content but are linking to the *original* articles on the IDEAS classic site. The links are of course bad at this point. But, if you look at this PR, you will see that for each of the articles I changed, I also removed a file in CuratedContent folder that was linking to the same article on the old IDEAS classic site. I think we all need to pay attention to this and remove those *companion* CC articles we find.

**Comment by markcmiller86** [comment]
> * Do we remove the "How To" branding of the article? Effects titling
>    You mean the "howto" logo? Just delete it.

I mean the characterization of the article as a "How to doc" and the use of `How to` in the title and other places in the article. I think that should be removed but thats just me. What do others think?

**Comment by rinkug** [comment]
> > * Do we remove the "How To" branding of the article? Effects titling
> >   You mean the "howto" logo? Just delete it.
> 
> I mean the characterization of the article as a "How to doc" and the use of `How to` in the title and other places in the article. I think that should be removed but thats just me. What do others think?

I removed how to from the title and other places. I just added the track: how to and moved the document to the blog folder.

**Comment by markcmiller86** [comment]
> I just added the track: how to and moved the document to the blog fold

Ok, well, I did everything you did but did not move them to blog. I will do that in this PR too.

**Comment by rinkug** [comment]
Can you attach the preview label and check if it works and shows up in preview site?

**Comment by bernhold** [comment]
> > * Does the article have a _companion_ curated content that pointed at the old IDEAS classic site? If so, remove it
> >   What do you mean?
> 
> What I mean is...there are CC articles that are effectively _duplicates_ of this content but are linking to the _original_ articles on the IDEAS classic site. The links are of course bad at this point. But, if you look at this PR, you will see that for each of the articles I changed, I also removed a file in CuratedContent folder that was linking to the same article on the old IDEAS classic site. I think we all need to pay attention to this and remove those _companion_ CC articles we find.

Issue #1877 lists BSSw.io articles that link to i-p.o content that no longer exists. I have not looked at the articles, but this seems like a good place to look for "companion cc" articles.

**Comment by bernhold** [comment]
> > * Does the DOE admonishment need to remain? I think so but lets be sure.
> 
> The mention about funding? You can remove it. Everything on this site is funded through DOE anyways IMHO.

I would like to push back on Rinku's response:  We've always tried to case BSSw.io as a *community* site, *not* a DOE site.  I've always disliked having the sponsor logos in the footer.  (Matt from Sandbox argued that the DOE association would give the site additional credibility.) From the overall site perspective, I think we should tend to move away from sponsor labeling.

In individual articles, we generally don't include sponsor acknowledgments either, though I think there may be a couple of blog articles that include them.  I think we should prefer *not* to include sponsor acknowledgments in content, though if the contributor feels strongly enough, we can retain them.

My two cents

**Comment by markcmiller86** [comment]
> I would like to push back on Rinku's response:

Which part of her response? I think @rinkug said to *remove* the DOE thingy (which I incorrectly characterized as an *admonishment*...its actually an *auspices* statement I think). And, I think you are agreeing that we should *remove* these, right?

Unfortunately, I do not think I am allowed to remove *auspices* from any content I handled through LLNL's formal R&R processes. The only example I am aware of that I produced is the article about [ALE3D and SIERRA replacing `master`/`slave` terminology](https://bssw.io/blog_posts/experiences-replacing-master-slave-terminology-in-ale3d-and-sierra)

**Comment by markcmiller86** [comment]
> Can you attach the preview label and check if it works and shows up in preview site?

Yes. I can. Anybody who is an EB member can, I think.

**Comment by bernhold** [comment]
The part that says "Everything on this site is funded through DOE anyways IMHO."

As to what you call the "auspices", I admit to not fully understanding the rules.  I inquired at ORNL a while back and found that the contract acknowledgment was *not* required on anything we publish, though I'd been told for 20 years that it was.  We don't have the same level of rigor in the review and release process and are not required to document it externally in any case.  I do know that for some other (weapons) labs, authors have been okay with the R&R info appearing in comments, so that it would not be visible on the production site, but is visible in the source in the repository.  But authors not objecting is not a guarantee that it is actually consistent with the rules.

**Comment by markcmiller86** [comment]
> authors have been okay with the R&R info appearing in comments, so that it would not be visible on the production site, but is visible in the source in the repository.

Although that seems reasonable, I think means the main purpose of including such a statement is entirely lost...most consumers would never know it.

**Comment by markcmiller86** [comment]
> Frankly, I don't think the general public cares at all whether something has been through an internal review process :-)

Yeah, I agree. And, that isn't want the auspices statement is saying, IMHO. Its saying who paid for the work. And, I do think some readers may want to know that and I think our respective institutions may want it to be known also (or at least easily knowable for those who want to know).

In any event, my biggest concern is the former one you mention...that someone instructed me to include it as part of a review process and removing it now is not consistent with that instruction.

**Comment by bernhold** [comment]
Except that those contract acknowledgments don't actually specify who paid for the work either.  It is the management & operations contract identifier for the laboratory at which the work was done.  It is, in essence, the operating authority for the lab. The funding that paid for the work is a separate matter from the M&O contract.  Often it is DOE funds, but which part of DOE?  But the same contract acknowledgment also applies even the funding came from another government agency or industry through the work-for-others process.  So it really doesn't tell you anything about the funding.  In papers, we often add additional text to acknowledge the actual funding source.  But that's not in the line you're talking about in the BSSw.io article. 

As I said, I'd been told by my managers for 20 years that we had to acknowledge the M&O contract in our publications.  And then something came up that actually caused me to look closely at the written requirements and I found no such requirement.  And when I inquired, nobody was aware of such a requirement.  I'm not saying this is the case for LLNL or any of the other labs.  But it is what I discovered at ORNL.  The emperor acknowledges no clothes!

**Comment by markcmiller86** [comment]
@rinkug what should I be looking for regarding these article revisions on the preview site. I mean I *do* see them there. However, I do not see *How to tracking* there. But, I think I recall that is on a version of the site that is not yet live, correct?

**Comment by markcmiller86** [comment]
> I'm not saying this is the case for LLNL or any of the other labs.

I guess I'd be interested if same is true at LLNL but I don't have the bandwidth to do the legwork on that. I just accept what others tell me. And, for released work as recently as a few weeks ago, I was told (as I always am) to include an auspices statement. Having been told that for work I had reviewed and then published, I do not want the published piece to now not reflect those instructions.

> Except that those contract acknowledgments don't actually specify who paid for the work either.

I feel like we're splitting hairs here. I am not so much referring to the contract number as I am to "US", "DOE" and "LLNL" (all of which are specified in LLNL auspices). Which arm of DOE or which FOA call or which specific project in all likelihood have no meaning to 99.9% of readers. Ultimately, we could just say "work paid for by the US taxpayers" too but I am not suggesting we do.

**Comment by rinkug** [comment]
> @rinkug what should I be looking for regarding these article revisions on the preview site. I mean I _do_ see them there. However, I do not see _How to tracking_ there. But, I think I recall that is on a version of the site that is not yet live, correct?

Thats right

**Comment by rinkug** [comment]
@markcmiller86 I am done with feedback. Pls see PR #1915

**Comment by rinkug** [comment]
> But, I vote we DO NOT spell check commit messages.

I agree. I opened an issue for this #1916

**Review by rinkug — APPROVED** [review]

**Pull request merged**
