### PR TITLE
Create event for HiRSE webinar 26 in Feburary

### PR DESCRIPTION
**Pull request by rcaspart**
By making a submission here, you agree to [BSSw.io content licensing terms](https://github.com/betterscientificsoftware/bssw.io/blob/main/TERMS.md).

# Description

EB Member: @bartlettroscoe 

Resolves #`<issue-id>`

`<Other minimal information about the PR.>`

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* ~~[] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.~~
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: I rebuilt the preview site and we can see this article listed under the events:

* https://preview.bssw.io/events

as:

image

@betterscientificsoftware/bssw-editorial-board, the event text looks okay to me, but if someone else wants to take a quick look before we merge, let me know.  Otherwise, this event is only 12 days away, so I think we should merge this today (but it will not go out in a bssw.io digest email until after the event is over).

**Comment by rcaspart** [comment]
Thanks a lot @bartlettroscoe , looks perfectly fine from my side.
Unfortunately we are a bit out-of-sync with the digest, but we are working on aligning this better in the future.

**Comment by pagrubel** [comment]
Not sure if it is me, but I could not actually find how to join the event.

Pat

From: "Roscoe A. Bartlett" ***@***.***>
Reply-To: "betterscientificsoftware/bssw.io" ***@***.***>
Date: Thursday, February 15, 2024 at 11:42 AM
To: "betterscientificsoftware/bssw.io" ***@***.***>
Cc: "Grubel, Patricia A" ***@***.***>, Team mention ***@***.***>
Subject: [EXTERNAL] Re: [betterscientificsoftware/bssw.io] Create event for HiRSE webinar 26 in Feburary (PR #2007)


FYI: I rebuilt the preview site and we can see this article listed under the events:

  *   https://preview.bssw.io/events<https://urldefense.com/v3/__https:/preview.bssw.io/events__;!!Bt8fGhp8LhKGRg!EjQk_IO3SV2FyqPuklCJAAbdxCJzWmWlnsFMYIPqkx9K9Ub5MmCF3DSf5dMvqKCDIc-TXgptB6ZVOVtrlMZdWhXsLw$>

as:

image.png (view on web)<https://urldefense.com/v3/__https:/github.com/betterscientificsoftware/bssw.io/assets/1959736/2854b361-936d-40cb-9993-e62e8e9be2de__;!!Bt8fGhp8LhKGRg!EjQk_IO3SV2FyqPuklCJAAbdxCJzWmWlnsFMYIPqkx9K9Ub5MmCF3DSf5dMvqKCDIc-TXgptB6ZVOVtrlMbYI040bQ$>

@betterscientificsoftware/bssw-editorial-board<https://urldefense.com/v3/__https:/github.com/orgs/betterscientificsoftware/teams/bssw-editorial-board__;!!Bt8fGhp8LhKGRg!EjQk_IO3SV2FyqPuklCJAAbdxCJzWmWlnsFMYIPqkx9K9Ub5MmCF3DSf5dMvqKCDIc-TXgptB6ZVOVtrlMZHhdSKVw$>, the event text looks okay to me, but if someone else wants to take a quick look before we merge, let me know. Otherwise, this event is only 12 days away, so I think we should merge this today (but it will not go out in a bssw.io<https://urldefense.com/v3/__http:/bssw.io__;!!Bt8fGhp8LhKGRg!EjQk_IO3SV2FyqPuklCJAAbdxCJzWmWlnsFMYIPqkx9K9Ub5MmCF3DSf5dMvqKCDIc-TXgptB6ZVOVtrlMYuOGURtQ$> digest email until after the event is over).

**Comment by bernhold** [comment]
@pagrubel the event summary includes a "Request connection information" field with an email to contact.  Is there different language that would make that more obvious?

They also maintain an online calendar for this series, and those events list the connection info too.  I had originally been somewhat resistant to referencing it because there didn't seem to be a way to link specifically into the event (and you might even have to jump the calendar ahead to the next month before you see it).  But I was looking at it again, and it seems that you can link to the view of the calendar that has the event open.  Even in that view, you have to scroll down through the event description to get to the connection information, but it is there.  So I'm now inclined to try linking to that and providing the email address as a backup.  The one for the upcoming webinar is <https://b2drop.eudat.eu/apps/calendar/p/Z9NWzFdrS8fAXPd9/dayGridMonth/now/view/sidebar/L3JlbW90ZS5waHAvZGF2L3B1YmxpYy1jYWxlbmRhcnMvWjlOV3pGZHJTOGZBWFBkOS80NTA3N0JGNy1DQUY1LTRFNTItQjA4OS1CM0Y0MzBGMTg0MjcuaWNz/1709042400>.  Please check that it works for you too.

**Pull request merged**
