### PR TITLE
Move wikize_refs.py to utils/, add some tests, change to argparse, edits to doc (#363, #702)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@markcmiller86 

This PRs make the following changes to the PR #718 (and is pointed to that PR branch) (which addresses #363, #702):  

* Move `wikize_refs.py` to `bssw.io/utils/` dir (see 0c171fb12a6a5ee73836bf9b5b641a062d8ad7b8)
* Add some basic system-level tests for `wikize_refs.py` based on the existing files `bssw.io/Articles/Blogs/ReferencesInMarkdownHybridApproach[-wikized].md`.
* Change from 'optparse' to 'argparse' (please review commit 6862da564b83d8981ce88b8d0c2c34cc6d44b5fe, not the full patch shown in this PR which is not helpful since the file moved).
* Small edits to the document `bssw.io/Articles/Blogs/ReferencesInMarkdownHybridApproach[-wikized].md`

One thing that I could not figure out was the logic about "Handle an isoloated -o / --outfile (which means to use default name of output file)".  I commented that block of code out since the all the basic tests cases that I could figure out all pass.   What use case is this supposed to support and what is the expected behavior?  I need to know that in order to write some tests so that I can modify the argparse implementation to match expected behavior.

One way to do this is to checkout this branch, revert the commit 6862da564b83d8981ce88b8d0c2c34cc6d44b5fe, then add a test cases for when this logic should be executed and pin down the expected behavior.  Then one can revert the revert commit and get the argpase implementation working for these cases as well.

### CODE REVIEW

**Comment by markcmiller86** [comment]
Quick question...why so much CMake logic to handle testing of a python tool? I was thinking it would involve just adding another python script that tested it which I anticipated being < 100 lines.

**Review by markcmiller86 — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
> Quick question...why so much CMake logic to handle testing of a python tool? I was thinking it would involve just adding another python script that tested it which I anticipated being < 100 lines.

If you are just running a command-line tool and diffing output, a cmake/ctest solution is likely better than using a raw Python test driver.  And with ctest, you can run the tests in parallel, post to CDash if you want (at some point).  If you look at what the system-test driver script does (removes and creates the test subdir, runs the command, print if it fails, diff output files, etc.) then the a python system-level driver would not be much shorter.  The size of those files are just:

```
http://cloc.sourceforge.net v 1.55  T=0.5 s (4.0 files/s, 436.0 lines/s)
---------------------------------------------------------------------------------------------
File                                                      blank        comment           code
---------------------------------------------------------------------------------------------
utils/tests/CMakeLists.txt                                   16              8             61
utils/tests/run_wikize_ref_diff_test.cmake                   24             63             46
---------------------------------------------------------------------------------------------
SUM:                                                         40             71            107
---------------------------------------------------------------------------------------------
```

So there is a lot of blank space and a lot of comments.  The actual test code is around 100 lines all together (for system-level tests).  Adding more system-level test cases involves very little extra CMake code (and Python can't really improve too much on that).

For unit tests, there will be a separate `wikize_refs_unit_tests.py` program that will run as a single ctest test.   I will add the beginnings of that to show how that works.

BTW, I am basically following the process for adding tests to an untested code in:

* http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf

Here we are on step **3. Add system-level tests** and we are using the "system-level test harness" ctest tool for this purpose.  (CTest is a better choice for a system-level test harness than raw Python IMHO).

The unit test program `wikize_refs_unit_tests.py` gets us into step **4. Add integration and unit tests**.

There is a lot of behavior in this tool that is not currently being tested very well with just these simple system-level tests.  We need to define what types of input is and is not acceptable and what the error messages will be when users screw up (and they will screw up).  But we can add those based on risk (and the risk for various defects is low right now given the nature of this tool and the very low number of current users).

**Comment by markcmiller86** [comment]
Ok, so I guess the short answer to *why CMake?* is that you wanna use CTest, right?

I wonder if everyone here is going to be comfortable with that? I mean, I don't think anyone would object to learning either CMake or CTest with good reason.

I just wonder if introducing these dependencies, as well as any implied demands upon others here to have or develop the expertise to maintain them is a bigger conversation than just getting some level of testing working for this script? I think that is especially true given that there is a simpler alternative...a python test driver script that exits with 0 on success and 1 on any failure and/or issues a useful error message upon failure.

**Comment by bartlettroscoe** [comment]
> Ok, so I guess the short answer to why CMake? is that you wanna use CTest, right?

@markcmiller86, right, cmake is just an easy way to generate the CTestTestfiles.cmake files you need to run ctest.  Also, cmake -P scripts are a nice portable way to run more complex tests (like in this case).

> a python test driver script that exits with 0 on success and 1 on any failure and/or issues a useful error message upon failure

If you would like to replace the `run_wikize_ref_diff_test.cmake` with `run_wikize_ref_diff_test.py` then that is fine with me.  If you want to get rid of cmake/ctest altogether and use the Python unittest module to define and run each test, then that is possible as well (and I have done that too and there are advantages to that as you mention).  In the end, the amount of code will will be pretty similar and will look about the same.  But from experience, you don't just want to check for 0 return codes.  That makes the test pass trivially by putting a return early in the driver or some bad logic that does not check the return code correctly.  Robust tests are better IMHO.

**Comment by bartlettroscoe** [comment]
@markcmiller86, I will post the updated code and system-level tests using cmake/ctest.  If someone want to replace these with a pure Python solution, then that is fine with me.  But in general, if you are running tests, at some point ctest is not bad option somewhere in the devops toolchain (since CDash comes for about free).

**Comment by markcmiller86** [comment]
Should I merge now?

**Comment by bartlettroscoe** [comment]
> Should I merge now?

@markcmiller86, let me update the behavior of the script as per [above](https://github.com/betterscientificsoftware/bssw.io/pull/727#commitcomment-47764879) and push the commits first.  I have the tests updated now I just need to update the code so the tests pass again.

**Comment by bartlettroscoe** [comment]
@markcmiller86, as of commit https://github.com/betterscientificsoftware/bssw.io/pull/727/commits/ab8e033825d611e85c72cdc45425895a822d0e2b that I just pushed, the `wikze_refs.py` script should have the updated behavior we discussed [above](https://github.com/betterscientificsoftware/bssw.io/pull/727#commitcomment-47764879) and should have pretty solid system-level tests for those use cases.

To view the diffs that I made to the `wikize_refs.py` tool, you want to pull this branch and then run:

```
$ git diff HEAD --not 0c171fb1 -- utils/wikize_refs.py
```

Otherwise, you can't effectively see the changes in this PR since the file was moved.  The changes are very minor.

I think this is ready to merge and after that, I think we can merge the parent PR #718.  We can add a unit test harness and the beginning of unit tests later in follow-up PRs.

**Comment by markcmiller86** [comment]
I will be without my machine for the next several hours when I get it back I will do this merge or you are welcome to do it if you prefer. Thanks for all of the work on this!

Sent from my iPhone

On Mar 3, 2021, at 8:48 AM, Roscoe A. Bartlett <notifications@github.com> wrote:

﻿

@markcmiller86<https://urldefense.us/v3/__https://github.com/markcmiller86__;!!G2kpM7uM-TzIFchu!iguvz5EE5dMGR8X9p0Apc-Tee3Ys8kf7jDSStlxX920y_bA9NO1XGC8-adeaJJy1FQ$>, as of commit ab8e033<https://urldefense.us/v3/__https://github.com/betterscientificsoftware/bssw.io/commit/ab8e033825d611e85c72cdc45425895a822d0e2b__;!!G2kpM7uM-TzIFchu!iguvz5EE5dMGR8X9p0Apc-Tee3Ys8kf7jDSStlxX920y_bA9NO1XGC8-add7cO-o6g$> that I just pushed, the wikze_refs.py script should have the updated behavior we discussed above<https://urldefense.us/v3/__https://github.com/betterscientificsoftware/bssw.io/pull/727*commitcomment-47764879__;Iw!!G2kpM7uM-TzIFchu!iguvz5EE5dMGR8X9p0Apc-Tee3Ys8kf7jDSStlxX920y_bA9NO1XGC8-adeBZ_nbYg$> and should have pretty solid system-level tests for those use cases.

To view the diffs that I made to the wikize_refs.py tool, you want to pull this branch and then run:

$ git diff HEAD --not 0c171fb1 -- utils/wikize_refs.py


Otherwise, you can't effectively see the changes in this PR since the file was moved. The changes are very minor.

I think this is ready to merge and after that, I think we can merge the parent PR #718<https://urldefense.us/v3/__https://github.com/betterscientificsoftware/bssw.io/pull/718__;!!G2kpM7uM-TzIFchu!iguvz5EE5dMGR8X9p0Apc-Tee3Ys8kf7jDSStlxX920y_bA9NO1XGC8-addps7V6GQ$>. We can add a unit test harness and the beginning of unit tests later in follow-up PRs.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Pull request merged**
