### PR TITLE
revisions to WhatIs on PeerCodeReview

### PR DESCRIPTION
**Pull request by rinkug**
Suggestions for Peer Code Review article #1678

### CODE REVIEW

**Comment by rinkug** [comment]
@bartlettroscoe : Not sure why I cannot see my stacked PR revisions on preview: https://preview.bssw.io/items/what-is-peer-code-review

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe : Not sure why I cannot see my stacked PR revisions on preview: [preview.bssw.io/items/what-is-peer-code-review](https://preview.bssw.io/items/what-is-peer-code-review)

@rinkug, I see the problem:

https://github.com/betterscientificsoftware/bssw.io/blob/0780f0e40a145dbde8f61cc7bc11fd6532fe8c3f/.github/workflows/merge-pr-to-preview.yml#L7

I will remove that constraint.  Since someone has to explicitly set the `preview` label, we will not be getting branches merged to `preview` by accident.

**Comment by bartlettroscoe** [comment]
@rinkug, I updated the [workflow](https://github.com/betterscientificsoftware/bssw.io/blob/master/.github/workflows/merge-pr-to-preview.yml) to not have the target branch constraint, I added a new commit to this PR (which should trigger the `pull_request_target` type `synchronize`, and I added and removed the `preview` label and the action never even ran.  Not sure what is going on but I will do some more experimentation.

**Comment by bartlettroscoe** [comment]
CC: @markcmiller86, @bernhold, @betterscientificsoftware/bssw-editorial-board 

@rinkug, was finally able to get this stacked PR to merge to 'preview'.  What I had to do was to rebase the branch `whatis-peer-code-review` from PR #1678 on top of `master` (after I pushed the commit cc56b41a031286b67e6278367d73b7b8bd79abad to `master`) and forced pushed the branch `whatis-peer-code-review`.  Then I rebased your branch `rinkug-patch-3` from this PR #1679 on top of `whatis-peer-code-review` and force pushed.  And with that, it triggered the the [`merge-pr-to-preview.yml`](https://github.com/betterscientificsoftware/bssw.io/blob/master/.github/workflows/merge-pr-to-preview.yml) workflow a shown [here](https://github.com/betterscientificsoftware/bssw.io/actions/runs/4961722745) and you can see the version of the file `merge-pr-to-preview.yml` used for that action job [here](https://github.com/betterscientificsoftware/bssw.io/actions/runs/4961722745/workflow).

So it seems that GitHub Actions will use the version of a workflow `*.yml` file from the topic branch in the PR and not what is on `master` to run a workflow.  That was verified when I created the branch and PR #1680 which I made the target 'master' which merged to 'preview' correctly but the version of the workflow file `merge-pr-to-preview.yml` for that action is shown [here](https://github.com/betterscientificsoftware/bssw.io/actions/runs/4961686366/workflow?pr=1680) showing:

```
name: Sync pull request to preview
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, labeled]
    branches:
      - master
jobs:
  ...
```

That is **NOT** what was on the 'master' branch at the time which was:

```
name: Sync pull request to preview
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, labeled]
jobs:
  ...
```

I don't know why GitHub Actions acts this way but one can argue that is okay since you can always just merge and rebase your branches with 'master' if you want to run with what is on 'master'.  I guess without that, how could you test workflows before merging to 'master'?

I just asked Google Bard this question:

> With GitHub actions, what version of a workflow file is used for a pull request?  Is it the version on the pull request branch or the version on the target branch (i.e. master)?

and it responded:

> The version of the workflow file that is used for a pull request is the version on the pull request branch. This is because the workflow is triggered by the pull request event, and the pull request event provides the contents of the pull request branch. The target branch is not involved in the workflow trigger, so its version of the workflow file is not used.
>
> For example, if you have a workflow file named .github/workflows/my-workflow.yml on the main branch, and you open a pull request from the feature branch, the workflow that will be run is the one in .github/workflows/my-workflow.yml on the feature branch.
> 
> You can use the branches keyword in the on event to specify that a workflow should be run on multiple branches. For example, the following workflow will be run on the main and feature branches:
>
> ```
> on:
>  pull_request:
>   branches:
>     - main
>     - feature
> ```

I don't know where Brad got that explanation from but it seems to be seems to be consistent with the behavior I just observed.

Now we know (or at least now I know in case others already knew this).

**Comment by bartlettroscoe** [comment]
> What I had to do was to rebase the branch ...

And that breaks the 'preview' branch 😂  I will fix the preview branch and force push.  In the future, we can do the same thing by merging 'master' into these branches.  That has the same effect and does not break the 'preview' merge 👍

**Comment by bartlettroscoe** [comment]
FYI: I reran the merge-to-preview GHA manually for these two PRs and now all of the commits are showing up on 'preview' as shown at:

https://github.com/betterscientificsoftware/bssw.io/commits/preview

showing:

image

Merging spacked PRs to 'preview' should go smoothly from here on.

**Review by bartlettroscoe — APPROVED** [review]
LGTM

**Pull request merged**
