### PR TITLE
SIAM CSE21 retrospective blog article

### PR DESCRIPTION
**Pull request by bernhold**
# Description

EB Member: @curfman 

Addresses issue #`<issue-id>`

`<Other minimal information about the PR.>`

## PR checklist for files displayed on bssw.io site

* [x] `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* [x] Assign this PR to the EB member `<eb-member-id>`.
* [x] Assign this PR to the author of the PR `<pr-author-id>`.
* [x] Add label `content: <content-type>` for the type of contribution.
* [x] Add to Project `Content Development` (see [Content Development]).
* [x] Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] Add one or more Reviewers.
* [x] Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* ~~[ ] Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] Make any final changes to the PR based on feedback.
* ~~[ ] Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] Rebuild [preview] site and re-confirm content looks correct.
* [x] Ensure at least one reviewer signs off on the final changes.
* [ ] Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] Move the PR to "Ready to Publish" in [Content Development].
* [ ] Assign to one of the site maintainers to carry out final publication steps.
* [ ] Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] Merge PR. Should automatically move to "Done" in [Content Development].
* [ ] Verify new new contribution shows up on [bssw.io] as expected.

NOTE: Optional checklist items can be striked out with adding `~~` to beginning and end of the checklist item as `* ~~[ ] <checklist-item>~~`.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bernhold** [comment]
Need to fix contributors info -- somehow.  In the blog list page, it is just "BY" without any author.  In the article itself, it shows up as "AUTHOR CONTRIBUTED BY THE BSSW COMMUNITY".  Asked Matt and Clara for help figuring out a solution.

**Comment by bartlettroscoe** [comment]
@bernhold, looks good to me (but I only read the intro and the text for my MS).  Thanks for putting this together!

**Comment by hnamLANL** [comment]
Thanks @davidbernholdt !  Looks good, small fix - 

Need to fix typo - 2nd paragraph  "And this year, with the help of sixteen organizeres" - organizers

On my BSSw Fellowship session, Damian and Kyle are listed as organizers, but really weren't.  Not sure why the system picked them out that way from my original submission.  Can I drop them or add the other two (Cindy, Nasir) to the list.

**Comment by bernhold** [comment]
> On my BSSw Fellowship session, Damian and Kyle are listed as organizers, but really weren't. Not sure why the system picked them out that way from my original submission. Can I drop them or add the other two (Cindy, Nasir) to the list.

I was going by what appears in the SIAM conference management system.  I wondered about it.  If that was some kind of mistake, I can list just you.

**Comment by bartlettroscoe** [comment]
NOTE: Given the merge of #765, I retroactively copied in the PR checklist for bssw.io files and I added the `preview` label so this PR branch will continue to be merge to the 'preview' branch.

**Pull request merged**
