### PR TITLE
Add documentation for preview branch workflow

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@betterscientificsoftware/bssw-editorial-board 

Now that we are actually using the "preview" branch workflow suggested in #330, we should document it (so everyone can look if they want).  

This was the branch I created a long time ago that explains how it works.  This branch has been updated for the current status of the preview branch workflow..  The file can be viewed at [bssw_pr_preview_branch.md](https://github.com/bartlettroscoe/bssw.io/blob/330-preview-pr-workflow/docs/pages/bssw/bssw_pr_preview_branch.md).

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@markcmiller86, @rinkug, @bernhold, I think this PR and file [bssw_pr_preview_branch.md](https://github.com/bartlettroscoe/bssw.io/blob/330-preview-pr-workflow/docs/pages/bssw/bssw_pr_preview_branch.md) is ready to merge.  Please review and provide suggestions.

NOTE: This PR is showing a merge failure to 'preview' but who cares.  This file is not meant to be viewed on the preview.bssw.io site.

**Comment by markcmiller86** [comment]
> NOTE: This PR is showing a merge failure to 'preview' but who cares. This file is not meant to be viewed on the preview.bssw.io site.

Ran into same problem with #725

**Review by rinkug — APPROVED** [review]

**Comment by rinkug** [comment]
This PR has been merged in the EB docs directory.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Pull request merged**
