### PR TITLE
CC: Technical Debt in Practice: How to Find It and Fix It (#2194)

### LINKED ISSUE #2194: CC: Technical Debt in Practice: How to Find It and Fix It
I have been reading the book [Technical Debt in Practice: How to Find It and Fix It](https://www.amazon.com/Technical-Debt-Practice-How-Find/dp/0262542110/ref=asc_df_0262542110?mcid=85e6c3ae9fa838adb777ff20c2fb2cc6&hvocijid=15264663257703520049-0262542110-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=692875362841&hvpos=&hvnetw=g&hvrand=15264663257703520049&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9008023&hvtargid=pla-2281435177858&psc=1).  I have read enough to be able to recommend it.  I have actually learned more than I thought I would about the topic.  I will highlight that in my CC article.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @rinkug 

Resolves #2194

Provides a good overview of the book "Technical Debt in Practice: How to Find It and Fix It".  It is a bit long, but you can view this as an abbreviated "CliffsNotes" for the major content of the book.  (This CC article is not substitute for the content of the book but if the reader only reads this CC article, they should come away with some useful information, and know where to go for more details.)

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by rinkug** [comment]
@bartlettroscoe : Very interesting read and very thorough (as you usually are). Pls let me know when its ready to merge. I did a review and LGTM as is.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe : Very interesting read and very thorough (as you usually are). Pls let me know when its ready to merge. I did a review and LGTM as is.

I think want to add some section headings to help organize this better.  Otherwise, I would just read it over one more time.  I will do that today.

**Comment by rinkug** [comment]
> > @bartlettroscoe : Very interesting read and very thorough (as you usually are). Pls let me know when its ready to merge. I did a review and LGTM as is.
> 
> I think want to add some section headings to help organize this better. Otherwise, I would just read it over one more time. I will do that today.

Ok, the digest must go out tomm. If you cant do it tonight, I can find an existing article to highlight. And we put yours in the digest next month

**Comment by bartlettroscoe** [comment]
> Ok, the digest must go out tomm. If you cant do it tonight, I can find an existing article to highlight. And we put yours in the digest next month

@rinkug, whatever updates I do will be done today so this can go in the digest tomorrow.  So I will set the publish date to 12/19/2024?

**Comment by rinkug** [comment]
> @rinkug, whatever updates I do will be done today so this can go in the digest tomorrow. So I will set the publish date to 12/19/2024?

Yes, 12/19 date is good.

**Comment by bartlettroscoe** [comment]
@rinkug, this is ready to merge.  You can see the article on the preview site at:

* https://preview.bssw.io/items/technical-debt-in-practice-how-to-find-it-and-fix-it

I could fiddle with the formatting some more, but that is a tedious process.

**Pull request merged**
