### PR TITLE
Attempt adjust blog article to use refs.

### LINKED ISSUE #1308: Update blog article to use references
https://bssw.io/blog_posts/user-stories-in-scientific-software-development
https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/2022-04-user-stories.md

I tried to replace footnote-style references in the original with inline citations, but Matt thinks they're more distracting.  They also cause poor formatting in at least one case (strange line break).  So we should probably change the piece to use wikize-refs citations.

### PR DESCRIPTION
**Pull request by markcmiller86**
@bernhold does this fix #1308 for you?

### CODE REVIEW

**Comment by markcmiller86** [comment]
Note, I chose to keep two in-line refs because I felt like they were less citations and more FYI's.

**Comment by markcmiller86** [comment]
It seems to look ok to me on preview.

**Comment by markcmiller86** [comment]
@bernhold does this work for you?

**Comment by markcmiller86** [comment]
Hope I am not being a pest...ping @bernhold

**Comment by markcmiller86** [comment]
> markdown within these references isn't rendered properly

I believe we can just re-run `wikize_refs.py` with the `-t` option to do it that way instead (`-t` says to do two-column html).

**Comment by markcmiller86** [comment]
Oh, I guess that is indeed what you did 😉

**Comment by bernhold** [comment]
I did it manually.  But I think it looks okay now (check out the preview if you want: https://preview.bssw.io/blog_posts/user-stories-in-scientific-software-development).  Thanks for this improvement.  I'll merge this shortly, unless I hear back that you have concerns about what you see in preview.

**Comment by markcmiller86** [comment]
Nah. go ahaed if you are happy. Glad it is useful.

**Pull request merged**
