### PR TITLE
Create Inclusive Language Resources CC

### LINKED ISSUE #652: Inclusive Terminology in Software
As a results of Inclusive Minute and other discussions within IDEAS, we have a growing list of resources associated with "inclusive naming".  I think we should put them together into a curated content article so that others can more easily find them too.

* https://inclusivenaming.org/
* https://github.com/conscious-lang/conscious-lang-docs
* https://sddiproject.org/
* https://www.theopensourceway.org/ (?)
* https://tools.ietf.org/id/draft-knodel-terminology-00.html
* https://developers.google.com/style/inclusive-documentation

### PR DESCRIPTION
**Pull request by karbarz**
# Description 

Author: @rinkug 
EB member: @?

Resolves #652 

Initial draft of article - needs more work, but this is a skeleton with all the resources in table form

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [x] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

### CODE REVIEW

**Comment by markcmiller86** [comment]
I am going to go ahead and add some resources I found will drafting #1099 to this before we merge it.

**Comment by markcmiller86** [comment]
@bernhold and @curfman and @rinkug this now contains the additional resources I compiled with working on #1099.

I think this is ready but I had a question or two...

Do we have a specific selection of choices for the text we put in the `Focus` field? If so, I think the stuff I added may be a little askew of that.

**Comment by markcmiller86** [comment]
@rinkug I've added...

* deck text
* intro
* @karbarz and myself as contributors

I think its good to go.

**Review by bartlettroscoe — CHANGES_REQUESTED** [review]
The link:

* https://github.com/kubernetes/community/tree/master/wg-naming

appears to be broken.  That link should be fixed before this gets published.

Just a comment from looking over this but the article specifically mentions *Guru* as a word to avoid but none of the references provided in this CC article mention the word (at least not that I can find).  Several of the references do mention the words specifically called out *sanity check* and *grandfathered* however.

Just an FYI, but here is a reference for *Guru*:

* https://www.thesaurus.com/e/ways-to-say/stop-using-in-2020/

But that also brings in other words that are not called out in any of the other references given in this CC article.

**Comment by markcmiller86** [comment]
> The link:
> 
> * https://github.com/kubernetes/community/tree/master/wg-naming
> 
> appears to be broken. That link should be fixed before this gets published.

It looks like the Kubernetes language working group has become [deactivated](https://github.com/kubernetes/community/commits/master/archive/wg-naming/README.md) since that resource was included here. I suspect the reason is that the leader of that group is now leading the Inclusive Language Initiative's language working group.

I think the correct action is just to remove this resource from our list. We have the INI resource already.


> 
> Just a comment from looking over this but the article specifically mentions _Guru_ as a word to avoid but none of the references provided in this CC article mention the word (at least not that I can find). Several of the references do mention the words specifically called out _sanity check_ and _grandfathered_ however.

Just curious but did you audit all the resources here for `sanity check` and/or `grandfathered` as well? Or, did you just restrict your concerns to `Guru`? The purpose of the deck-text is to inspire a closer look and provoke thought. The previous phrase I had there was `low man on the totem pole` (thats actually a two-fer, gendered and cultural appropriation) but its far less commonly used than `Guru` and for that reason is less likely to inspire a closer look.

> 
> Just an FYI, but here is a reference for _Guru_:
> 
> * https://www.thesaurus.com/e/ways-to-say/stop-using-in-2020/
> 
> But that also brings in other words that are not called out in any of the other references given in this CC article.

Perhaps I am missing a requirement you seem to be inferring...that any word mentioned in BSSw prose must also be specifically addressed in at least one cited reference. I don't agree.

**Comment by bernhold** [comment]
I heard today about another resource that you might want to include.  INCITS is the organization that's responsible for US participation in ISO standards (like C, C++, Fortran and many others) and domestic IT standards.  INCITS has released "INCITS Principle of Inclusive Terminology" and more recently  "INCITS Inclusive Terminology Guidelines".  The [announcement](https://www.incits.org/news-events/press-releases/incits-issues-new-inclusive-terminology-guidelines-for-standards) has links to the current versions of both documents.  I'm not clear whether there is a page somewhere for this as an ongoing activity rather than the specific versions of specific documents.

**Comment by markcmiller86** [comment]
> I heard today about another resource that you might want to include. INCITS is the organization that's responsible for US

I added it but for some reason...I thought it was @bartlettroscoe that had mentioned it and so credited @bartlettroscoe in the commit message with a `(thanks Ross)` which must have seemed a bit confusing.

Anyways, its added now.

**Comment by bartlettroscoe** [comment]
Here is a fairly modest proposal from what appears to be a pretty large standardization organization (Internet Engineering Task Force (IETF)):

* https://tools.ietf.org/id/draft-knodel-terminology-02.html

An interesting discussion of this topic in this diverse community is in this New York Times article:

* https://www.nytimes.com/2021/04/13/technology/racist-computer-engineering-terms-ietf.html

**Comment by markcmiller86** [comment]
Thanks @bartlettroscoe. I added an entry for that resource as well.

**Comment by bernhold** [comment]
https://www.xsede.org/terminology may also be of interest

**Comment by bernhold** [comment]
https://www.acm.org/diversity-inclusion/words-matter

**Review by rinkug — APPROVED** [review]

**Review by rinkug — APPROVED** [review]

**Pull request merged**
