### PR TITLE
Update  How-tos and add tracks

### LINKED ISSUE #1558: Adding track meta to all relevant articles
Related to #699.

Context: Blogs, original articles, howtos, what-is will now be distinguished using "tracks" and all these articles will be available under https://bssw.io/blog_posts. To achieve this, we need to add the "track" metadata in these articles. Since we are touching all these articles, we may as well remove old obsolete metadata.

- **We need to add new *Track* metadata to everything in [Articles directory]**(https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles)
    Track: Deep Dive/How To/Community/Experience/Bright Spots

- **What meta should each file ideally have?** 
   Ideally each file should have the following metadata as listed in the [BSSw.io Editorial Guide](https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html): 
    Publish: yes
    Pinned: no
    RSS Update: 2023-01-11
    Topics: projects and organizations
    Track: 

  **We dont know how RSS feed behaved, so dont add RSS update if a file does not already have that.**

- **We need to remove old metadata**
   Please remove anything that is obsolete other than what is mentioned above.

- **Do articles need to move between folders?**
  Yes eventually, but lets leave that aside for now.

### LINKED ISSUE #1877: Need content to replace old i-p.o HowTo articles
**[UPDATE by Rinku on Dec 12 2023] Team members have been assigned what articles they are responsible for  and its being tracked in this [excel tracking file](https://docs.google.com/spreadsheets/d/1DnR7EJ4RScRrnekxz4RQ8F9GBhy8BhvODiPq3JqPagU/edit#gid=842716675).**

A number of BSSw articles link to HowTo (and related) content that was hosted on the old ideas-productivity.org Wordpress site, which is no longer available since we put the Jekyll site into production.  We need to

1) Republish that material on BSSw
2) Change the BSSw articles to point to the new versions

As of 13 Oct, the following BSSw.io articles needed attention:

BSSw URL | Old i-p.o URL
-----------|----------------
https://bssw.io/items/what-is-software-configuration-673277bd-6df9-474a-86c5-7e9ee40d784e | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-ConfigurationWhatIsSoftwareConfiguration-V0.2.pdf
https://bssw.io/items/how-to-write-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationHowToWriteGoodDocumentation-V0.1.pdf
https://bssw.io/items/what-is-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationWhatIsGoodDocumentation-V0.1.pdf
https://bssw.io/items/how-to-enable-performance-portability-for-cse-applications | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceHowToEnablePerformancePortability-V0.2.pdf
https://bssw.io/items/what-is-performance-portability-for-cse-applications-eccf9c55-c76a-42cc-81ec-a0d288a3eb0a | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceWhatIsPerformancePortability-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/what-is-cse-software-testing | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatAreSoftwareTestingPractices-V0.2.pdf
https://bssw.io/items/what-is-revision-control | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-VCWhatIsVersionControl-V0.1.pdf
https://bssw.io/items/how-to-configure-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-ConfigurationHowToConfigureSoftware-V0.2.pdf
https://bssw.io/items/what-are-interoperable-software-libraries-introducing-the-xsdk | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-InteroperabilityWhatAreInteroperableSoftwareLibraries-V0.2.pdf
https://bssw.io/items/how-to-do-version-control-with-git-in-your-cse-project | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-VCHowToVersionControlwithGit-V0.2.pdf

### PR DESCRIPTION
**Pull request by rinkug**
# Description
EB Member: @curfman 
Resolves #1558 
Resolves #1877 and ?

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [x] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [x] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

### CODE REVIEW

**Comment by markcmiller86** [comment]
I tried to debug and was not able to get too far.

@bartlettroscoe ... one thing that might be useful is to add a set of bullets here in a comment in this PR about how you go about diagnosing a merge conflict like this. I assume you cannot do it from the GitHub Action's log artifacts and wind up having to checkout and perform the git operations locally to see what is going on. If so, maybe just outlining the steps you take to do that here?

That way, we'll have a record of how to do this in case the *few* people who know how to do it are unavailable for extended periods after the new year.

**Comment by markcmiller86** [comment]
Ok, maybe I understand this better. I compared `preview` to `main` and saw that `preview` was 300 commits `ahead` (thats expected as we have in-flight PRs that have yet to be merged to `main`) and 3 commits `behind` (that is not expected as anything that is already on main should also be on preview...shouldn't it?)

So, I tried to *manually* merge `main` into `preview` on GitHub (#1907). That PR was almost immediately closed by automation...because we don't allow that.

But, it would appear both @rinkug and @markcmiller86 created PRs, did not apply the `preview` label and then later merged those PRs to main. So, I think that means `preview` never got updated with those changes and it means that main and preview were out of sync.

Well, wait a minute, they might be out of sync but there were no merge conflicts either.

**Comment by bernhold** [comment]
The preview label only matters for content processed through the front-end for the site.  For the EB docs, it is irrelevant.

**Comment by bernhold** [comment]
See the email I sent to the eb list about the sync problem.  The preview branch is maintained by a GH action, and there shouldn't be a need to update it manually (and, as Mark noticed, we try to prevent it).  Given the way we work, real merge conflicts are rare.  I believe that the easiest path forward when we have problems with the preview sync action is to delete and recreate the preview branch, per my email.

**Pull request merged**
