### PR TITLE
Adding CC for Coded Bias movie

### PR DESCRIPTION
**Pull request by markcmiller86**
This PR is based on issue #631.

Best if publish before Dec 14th.

### CODE REVIEW

**Review by rinkug — CHANGES_REQUESTED** [review]
* Please add a two liner deck as to why this article is of interest to our readers. See examples in [style guide](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_curated.html).

* We may need a couple of lines in the start of the main body, again, to indicate why this should be of interest to readers of our site which focuses on software sustainability. Perhaps something along the lines of "In the recent years, several teams in  HPC/CSE have been working on demonstrable inclusivity. This *Coded Bias* movie is a good resource to add to a team's Inclusion toolbox." (most folks may not know what is inclusion toolbox).

**Comment by markcmiller86** [comment]
@rinkug updated as per your requests. 

Some other thoughts
* My initial revision read a little to much like a movie review. I subdued it a bit.
* While trying to follow EB docs for deck text, I found that the hosted docs are
   * a bit hard to navigate
   * don't include explicit examples (or links to examples in our existing content)
   * have broken links
* I see instances of two different deck *tags* `<!-- deck start -->` and `<!-- deck end -->` and `<!-- deck text start -->` and `<!-- deck text end -->` among our existing content files. Which is correct going forward?
* We could maybe use a new high-level category on bssw.io for `Inclusion`
* In the updated table metadata, I followed the `Webinar` style except used *Film* in place of *Webinar*

**Review by rinkug — APPROVED** [review]
I have moved a sentence and add a sentence to explain inclusivity toolbox. Please merge if you agree

**Comment by rinkug** [comment]
> @rinkug updated as per your requests.
> 
> Some other thoughts

Lets discuss this further.

**Pull request merged**
