### PR TITLE
Handle ftp:// URLs in wikizer and fix associated content

### PR DESCRIPTION
**Pull request by markcmiller86**
While debugging `wikizer_refs.py` using `ApolloGuidanceComputerPart1.md`, I discovered that the tool didn't handle `ftp://` style urls correctly. I fixed that. I then re-generated the derived file `ApolloGuidanceComputerPart1-wikized.md` where an `ftp://` style ref had been used. While I was fixing that issue, I also fixed two unused footnotes in that file and replaced the use of `e` character for base-10 exponent in the table with `E` character. 

Resolves one of the items in #779

* [x] Set list of Reviewers (at least one).
* [x] Add to Project [BSSw Internal].
* [x] View the modified `*.md` files as rendered in GitHub.
* [x] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.
* [x] Watch for PR check failures.
* [x] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [x] Ensure at least one reviewer signs off on the changes.
* [x] Once reviewer has approved and PR check pass, then merge the PR.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Review by prwolfe — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
Seems like we should add an automated test for this use case.  The simplest thing to do would be to have a very simple `<base>.md` file that has `fthp://` in it and verify that the generated file `<base>-wikized.md` handles that correctly.  I can add that test for this case if it helps.

**Comment by bartlettroscoe** [comment]
BTW, I verified that the exiting tests still pass:

```
[rabartl@s1049009 utils (mcm86-12may21-wikizer-fixes)]$ ./run_tests.sh 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rabartl/BSSW.base/bssw.io/utils/build_tests
Test project /home/rabartl/BSSW.base/bssw.io/utils/build_tests
    Start 1: wikize_refs_help
1/7 Test #1: wikize_refs_help .............................   Passed    0.41 sec
    Start 2: wikize_refs_no_args_pass
2/7 Test #2: wikize_refs_no_args_pass .....................   Passed    0.36 sec
    Start 3: wikize_refs_no_args_fail
3/7 Test #3: wikize_refs_no_args_fail .....................   Passed    0.27 sec
    Start 4: wikize_refs_in_place
4/7 Test #4: wikize_refs_in_place .........................   Passed    0.38 sec
    Start 5: wikize_refs_in_place_no_save_orig
5/7 Test #5: wikize_refs_in_place_no_save_orig ............   Passed    0.31 sec
    Start 6: wikize_refs_explicit_out
6/7 Test #6: wikize_refs_explicit_out .....................   Passed    0.33 sec
    Start 7: wikize_refs_in_place_and_explicit_out_fail
7/7 Test #7: wikize_refs_in_place_and_explicit_out_fail ...   Passed    0.28 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   2.38 sec
```

**Comment by markcmiller86** [comment]
Given today's request to add logic to handle bssw.io metadata block, there will be another change to make here to handle that so hold off reviewing until I've pushed that too.

**Comment by bartlettroscoe** [comment]
> Given today's request to add logic to handle bssw.io metadata block, there will be another change to make here to handle that so hold off reviewing until I've pushed that too.

@markcmiller86, what direction are you going to go in?  Are you going to make the script look for the specific bssw.io meta-data comment block or make it more general by looking for the references section (with begin and end comment markers)?  It seems like the latter might be more robust to other types of issues as well.  Just curious.

**Comment by bartlettroscoe** [comment]
Also, we should add test cases for any behavior that is driving new development.

**Comment by markcmiller86** [comment]
> Also, we should add test cases for any behavior that is driving new development.

I am writing it to simply pass along all lines it finds *after* the link def blocks that are NOT recognized as *generated by* `wikize_refs.py`.

> Also, we should add test cases for any behavior that is driving new development.

Sure, but we all know that a best practice is for the test team to be wholly separate an independent from the development team. So, I am counting on *you* to write tests for it 😆

**Comment by bartlettroscoe** [comment]
> Sure, but we all know that a best practice is for the test team to be wholly separate an independent from the development team. 

The agile way is for one developer to write the code and the tests (i.e. using TDD) and then have another developer review the code and tests as a package.  I love reviewing tests :-)

But I am pretty sure you were just kidding about me writing the tests :-)

**Comment by bernhold** [comment]
@markcmiller86 I suggest a temporary hold on getting wikize to be more friendly to the metadata block.  Matt commented about the availability of some styling in the CSS for the reference section.  If we decide we want to use that, it might impact how we handle the metadata stuff too (or maybe not).   We should have a chance to find out more soon.  Lois didn't want to delay publishing the current blog article, however.

**Comment by markcmiller86** [comment]
@bernhold thanks for heads up. Ok, I think I will hold off. In crafting a fix to the meta-data block behavior (as well as cleaning up the code a bit), a better design has occured to me which I will capture notes about here...

Categorize lines (instead of whole blocks) in a `.md` file into one of the following...

* content
* author's original link definition
* generated by `wikize_refs.py`

All lines are read and categorized into these three. All the processing `wikize_refs.py` does is based on the data in the *author's original link definition* lines. All lines are re-output in the same order as input. Content lines get filtered for possible change in footnote ids. Author's original link definition lines get filtered to replace any footnote id (say `foo`) with `wikize-refs-foo` (effectively removing them from visibility in the rendered markdown. Generated lines get deleted and re-output beginning wherever they first appeared in the original sequence of lines.

This would avoid re-numbering of footnote ids, would avoid the need for knowing about any specialized content or blocks or worrying about ordering of content or blocks. It would allow content to come *after* generated blocks, etc. I think it would be a much better design.

**Comment by bartlettroscoe** [comment]
> a better design has occurred to me which I will capture notes about here

@markcmiller86, sounds good to me.  How would one go about writing unit tests for the various use cases here to ensure things don't slip through the cracks?  I would be interested in working with you on a unit testing infrastructure to make this code easier and faster to write and get correct, safer to maintain, and avoid future bugs for side cases not in typical `*.md` files (by creating crazy scenarios in unit tests).

**Comment by bernhold** [comment]
@markcmiller86 what is that status of this?  I think this PR addresses a specific issue that needs addressing, but the conversations seem to have gone off on a bit of a tangent.  Is that right?

Should we merge this and create a new issue for any tangential comments that actually need to persist?

**Comment by markcmiller86** [comment]
> Should we merge this and create a new issue for any tangential comments that actually need to persist?

I think that would be best.

**Comment by rinkug** [comment]
@markcmiller86 : Was this merged into master? I did a quick comparison of the changes made in this PR to the md file and it seems [the article](https://bssw.io/blog_posts/celebrating-apollo-s-50th-anniversary-when-100-flops-watt-was-a-giant-leap) on bssw.io already has these changes

**Comment by markcmiller86** [comment]
> @markcmiller86 : Was this merged into master?

Nope. I don't think you are seeing updated stuff on bssw.io either. I don't. I do see it on preview though.

There are now conflicts to resolve too. I can try to handle these this AM.

**Comment by markcmiller86** [comment]
@bartlettroscoe I have an issue where GitHub shows a merge conflict and so the `Merge pull request` button is grayed out but locally, I don't see a conflict. Maybe related to [this](https://github.community/t/merge-conflicts-on-github-not-locally/949). Should I just do the merge to master locally and push? Do permissions even allow that?

**Comment by bernhold** [comment]
@markcmiller86 in this case, GitHub is listing specific conflicted files.  That's not something we usually see when there are "false" merge conflicts.  Have you carefully checked the two files it mentions?  It looks like they were modified a couple of weeks ago, more recently than your PR was started.  So the conflicts may be real.  One place to look would be at the hero and other image references.  I think Rinku merged the PR to change all of the image references to the bssw.io repository from the separate images repository.

**Comment by bartlettroscoe** [comment]
> @markcmiller86 in this case, GitHub is listing specific conflicted files

@bernhold is correct.  This GitHub PR clearly lists the conflicting files:

image

which I verified locally:

```
[rabartl@s1049009 bssw.io (master)]$ git merge mcm86-12may21-wikizer-fixes
Auto-merging Articles/Blog/ApolloGuidanceComputerPart1.md
CONFLICT (content): Merge conflict in Articles/Blog/ApolloGuidanceComputerPart1.md
CONFLICT (modify/delete): Articles/Blog/ApolloGuidanceComputerPart1-wikized.md deleted in mcm86-12may21-wikizer-fixes and modified in HEAD. Version HEAD of Articles/Blog/ApolloGuidanceComputerPart1-wikized.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.

$ git status
On branch master
Your branch is up to date with 'github/master'.

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
        modified:   utils/wikize_refs.py

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by them: Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
        both modified:   Articles/Blog/ApolloGuidanceComputerPart1.md
```

The joys of [long-lived branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.s49ua5kor0n0).

**Comment by markcmiller86** [comment]
@bernhold I've resolved conflicts here and am ready to merge. But, I am getting a failed check during the merge of the pr to preview. I suspect its a false alarm. Is it ok to merge anyways?

**Comment by bernhold** [comment]
@markcmiller86 I fixed the conflicts by rebuilding preview from scratch.  Go ahead and merge.

**Review by bartlettroscoe — APPROVED** [review]
And here we see the file `ApolloGuidanceComputerPart1.md` updated and the `*-wikized.md` file removed.

**Comment by bartlettroscoe** [comment]
Is this ready to merge?  Can I click "Merge pull request"?

**Pull request merged**
