### PR TITLE
Added Github Link

### PR DESCRIPTION
**Pull request by karbarz**
Adding link to Ashley Barker's github

EB Member: @curfman 

Addresses issue # no current issue
From a discussion on Slack.

Small fixes to various articles - no checklist needed.

### CODE REVIEW

**Review by curfman — CHANGES_REQUESTED** [review]
Kasia -- Thanks for the edits; I see that most use the following style:
    [Ashley Barker](https://github.com/ashley08 "Ashley Barker Github profile")
Let's use this style consistently for all cases.  Thanks.

**Comment by karbarz** [comment]
> Kasia -- Thanks for the edits; I see that most use the following style:
> [Ashley Barker](https://github.com/ashley08)
> Let's use this style consistently for all cases. Thanks.

This has been completed.

**Comment by karbarz** [comment]
Sorry about the close - I hit the wrong button :(

**Comment by karbarz** [comment]
I checked the preview website while we were on the callt together - all links look good 
@rinkug

**Review by rinkug — APPROVED** [review]

**Pull request merged**
