### PR TITLE
Add license attestation

### LINKED ISSUE #905: More thoughtful handling of copyright?
We probably ought to be more thoughtful about copyright.  I believe that somewhere there is an assertion that the site/contents are under MIT license.  We don't get any sign-off from contributors.  We don't have any mechanism for recording permissions on reuse of images or such (though I think this is rare).  Etc.

On the other hand, any contributor license agreement puts us in a situation where lab authors would need to invoke their Legal departments.

And personally, I feel like a Creative Commons license is more appropriate for our *content*.

### PR DESCRIPTION
**Pull request by markcmiller86**
Resolves #905 

This PR is to address the issue where content submission is lacking attestation (by the author) of our licensing terms (currently MIT). We modify the following...

- [x] Issue templates: a lot of text in existing templates was either repetative or not helpful or links were bad. I adjusted to first include attestation of terms but also reducing wordiness.
- [x] pull request template: we agreed to move checklist out of template and reference it from the template and include license attestation verbiage too
- [x] Contributing pages actually hosted on site
- [x] internal docs
- [x] Marry David's own blog notes with the internal docs notes

1. A new top-level file, [`TERMS.md`](https://github.com/betterscientificsoftware/bssw.io/blob/mcm86-28Sep23-cpyright-attest/TERMS.md) (which ChatGPT helped me draft) was added to define what *submitting* content here means in terms of licensing the content.
   * Linking to `TERMS.md` from various places via an `https://` URL (e.g. through GitHub) means including the branch name, which is currently `master`. However, knowing that we are moving `master` to `main`, I have opted to link to it on `main`. So, those links will actually be broken until `master` is switched to `main`.
1. The content from `PULL_REQUEST_TEMPLATE.md` was split and moved to...
   * [internal docs checklist](https://betterscientificsoftware.github.io/bssw.io/bssw_intdocs_pr_checklist.html)
   * [content checklist](https://betterscientificsoftware.github.io/bssw.io/bssw_content_pr_checklist.html)
3. The content in all the issue templates was basically deleted and replaced with some very short text.
4. David's boilerplate text for blog author invites was added to the internal docs site [here](https://betterscientificsoftware.github.io/bssw.io/bssw_blogworkflow.html#author-invite-template)
5. I have temporarily switched the branch our internal docs site is rendered from to this branch so you can view it.

### CODE REVIEW

**Comment by markcmiller86** [comment]
FYI...you can view the internal docs update [here](https://betterscientificsoftware.github.io/bssw.io/bssw_blogworkflow.html) (I just temporarily pointed it at this PR's branch)

**Comment by markcmiller86** [comment]
The PR checklist stuff was split in two and put here..

* [internal docs checklist](https://betterscientificsoftware.github.io/bssw.io/bssw_intdocs_pr_checklist.html)
* [content checklist](https://betterscientificsoftware.github.io/bssw.io/bssw_content_pr_checklist.html)

**Comment by markcmiller86** [comment]
There is only one minor [change to live site](https://github.com/betterscientificsoftware/bssw.io/pull/1830/files#diff-45ac44c8beea358082a1832f5119a74c138b4c0a563a8f59eafad48d8af53cca) and so I don't think we need to go through preview stuff for this.

**Review by bartlettroscoe — COMMENTED** [review]
I skimmed this and it looks really good.  I will read over the new content in detail before I post my final review.

**Pull request merged**
