### PR TITLE
Jarrah42 patch 1

### PR DESCRIPTION
**Pull request by jarrah42**
# Description

EB Member: @curfman 

Addresses issue #929

Text and images for blog article.

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [x] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [x] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by elaineraybourn** [comment]
Hi @jarrah42 I reviewed your post as you requested. Overall it is a very nice piece and a quick read. Thanks on behalf of the team for pulling this together! My feedback below is as follows:

1. In the first sentence you may want to indicate that RYP was developed by the PSIP team which is part of IDEAS Productivity. 
2. In the second paragraph after the first sentence, I would cite the PSIP paper. Here is the correct citation:
Heroux M.A. et al. (2020) Lightweight Software Process Improvement Using Productivity and Sustainability Improvement Planning (PSIP). In: Juckeland G., Chandrasekaran S. (eds) Tools and Techniques for High Performance Computing. HUST 2019, SE-HER 2019, WIHPC 2019. Communications in Computer and Information Science, vol 1190. Springer, Cham. https://doi.org/10.1007/978-3-030-44728-1_6.
3. You discuss 7 steps, however, according to the paper and in other PSIP documentation (including our github pages for practice guides) there are 8 steps listed, so you may consider altering your text for consistency. 
4. As implied by the hero image -- RYP is for self-assessment, so you may want to clarify in the body of text, where you say "assessment"
5. In the final paragraph you could indicate how teams can contact the PSIP team for assistance with RYP, or questions. Providing the bssw.io/psip/ link and our github page is never a bad idea. :-)

**Review by elaineraybourn — COMMENTED** [review]
Hi @jarrah42 I reviewed your post as you requested. Overall it is a very nice piece and a quick read. Thanks on behalf of the team for pulling this together! My feedback below is as follows:

In the first sentence you may want to indicate that RYP was developed by the PSIP team which is part of IDEAS Productivity.
In the second paragraph after the first sentence, I would cite the PSIP paper. Here is the correct citation:
Heroux M.A. et al. (2020) Lightweight Software Process Improvement Using Productivity and Sustainability Improvement Planning (PSIP). In: Juckeland G., Chandrasekaran S. (eds) Tools and Techniques for High Performance Computing. HUST 2019, SE-HER 2019, WIHPC 2019. Communications in Computer and Information Science, vol 1190. Springer, Cham. https://doi.org/10.1007/978-3-030-44728-1_6.
You discuss 7 steps, however, according to the paper and in other PSIP documentation (including our github pages for practice guides) there are 8 steps listed, so you may consider altering your text for consistency.
As implied by the hero image -- RYP is for self-assessment, so you may want to clarify in the body of text, where you say "assessment"
In the final paragraph you could indicate how teams can contact the PSIP team for assistance with RYP, or questions. Providing the bssw.io/psip/ link and our github page is never a bad idea. :-)

**Comment by jarrah42** [comment]
Note, I've actually reduced the number of steps to 6 by combining "creating PTCs" with "record current PTC values" into one step. I think it makes it less confusing. The downside is it's different from the paper, but I don't think that's a big problem.

**Review by elaineraybourn — CHANGES_REQUESTED** [review]
@jarrah42 Please change "Sandia National Laboratory" to "Sandia National Laboratories"

**Comment by curfman** [comment]
publish!

**Pull request merged**
