### PR TITLE
Create 2021-05-RefTest_GPUProgramming.md

### PR DESCRIPTION
**Pull request by sbxchicago**
Test page for references in blog post.

Relates to #702

### CODE REVIEW

**Comment by markcmiller86** [comment]
Are we still having issues with refs in this article? If so, can I help?

**Comment by bernhold** [comment]
@rinkug we have not resolved the questions about reference formatting yet.  I would like to keep this PR until we have a chance to work with Matt on a path forward.  It is marked as Draft.

**Comment by bernhold** [comment]
Not on preview branch due to rebuild and I don't think it is needed at the moment.  To add it back, just add the preview label.

**Comment by bernhold** [comment]
No longer needed.

**Pull request closed without merging**
