### PR TITLE
Categories in Metadata Guide

### PR DESCRIPTION
**Pull request by karbarz**
Removed the "categories" tag from the main metadata section.
Redefined the "topics" tag to reflect the removal of "categories".
Moved "categories" information to the depreciated metadata section.

### CODE REVIEW

**Comment by karbarz** [comment]
References to the "categories" tag have been removed/changed where necessary in the following EB documents:

Common Styling
Curated Content
Original Article
Events
Metadata
Content Publishing

This refers back to one portion of issue #712 

@rinkug @curfman

**Comment by rinkug** [comment]
To discuss: Do we need to categories somewhere in docs to reflect historical usage.

**Review by rinkug — APPROVED** [review]

**Comment by karbarz** [comment]
> To discuss: Do we need to categories somewhere in docs to reflect historical usage.

I did move the "categories" section on the Metadata Guide to the depreciated metadata section so that it is still present, but not to be used. Would we still need to put it somewhere else in this case, or is that enough to reflect its historical usage?

**Review by rinkug — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
CC: @bernhold

@rinkug, @karbarz,

I think my PR #750 conflicted with the changes in this PR (which I had to fix manually when merging to the 'preview' branch).  This PR should get completed and merged to 'mater' or closed and removed from the 'preview' branch and not left out there to create more opportunities to create more merge conflicts.

It looks like this is ready to merge.  Can we go ahead and merge this to 'mater'?   I can fix the conflict and merge this.  Also, I have added this to the internal BSSw board to improve visibility.

Related to my epic SEPW-211

**Review by rinkug — APPROVED** [review]

**Comment by rinkug** [comment]
I have removed the conflict. Since this is ebdocs files, its ok for the checks to fail

**Pull request merged**
