### PR TITLE
Update image references to point to images/ directory (#738)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @bernhold 

Addresses issue #738

This PR copies in a few image files that were put in the separate [images](https://github.com/betterscientificsoftware/images) repo since the initial copy of that repo into the `bssw.io/images/` directory and then has a commit for the output of the script:

```
$ ./utils/convert_images_ref_to_rel_path_all.sh
```

The details are given in the expandable item below.

<details>

<summary><b>DETAILED NOTES:</b> (click to expand)</summary>

.

The images were initially copies from the 'images' repo to the 'bssw.io/images' directory in commit:

```
f51c5c7e "Copying in contents of images repo"
Author: David E. Bernholdt <bernholdtde@ornl.gov>
Date:   Thu Mar 18 08:34:48 2021 -0400 (3 months ago)
```

The last commit in the 'images' repo before that was:

```
153e85f "Add files via upload"
Author: Matthew Stone <junkmail@sandboxstudio.net>
Date:   Thu Mar 11 10:25:29 2021 -0600 (3 months ago)

A       Blog_0321_Siam.png
```

Since then, several commits have been made to the 'images' repo that edited the files:

```
$ git diff --name-status HEAD --not 153e85f
A       2021-04-SWMetricsInResearch-hero.png
A       Blog_0421_Metrics.jpg
A       KanbanAndScrumMakingTheBestOfBoth.png
M       README.md
```

Have any of those same files also been edited into the 'bssw.io/images' directory in the 'bssw.io' repo?  Here are the files edited in that directory since then:

```
$ git diff --name-status HEAD --not f51c5c7e -- images/
A       images/Blog_0421_Body_Retro.png
A       images/Blog_0421_Metrics.jpg
A       images/Blog_0521_CPU_GPU.png
A       images/Blog_0521_GPU.png
A       images/Blog_0521_GPU_CPU_.png
A       images/Blog_0521_IntroToGPU.png
A       images/Blog__0521_Icons.jpg
A       images/MolSSI-Logo.jpg
M       images/README.md
```

So it looks like the same two files have been edited in the two different repos since the initial copy 3 months ago:

```
A       Blog_0421_Metrics.jpg
M       README.md
```

I can just diff the file 'README.md'.  The file 'Blog_0421_Metrics.jpg' is more difficult since it is a binary file.  What are the commits on each side and by who?

In the 'images' repo we see:

```
$ git log-short --name-status HEAD --not 153e85f -- Blog_0421_Metrics.jpg
ed91dc5 "Add files via upload"
Author: Matthew Stone <junkmail@sandboxstudio.net>
Date:   Fri Apr 9 12:06:36 2021 -0500 (8 weeks ago)

A       Blog_0421_Metrics.jpg

39921e9 "Delete Blog_0421_Metrics.jpg"
Author: Matthew Stone <junkmail@sandboxstudio.net>
Date:   Fri Apr 9 12:06:19 2021 -0500 (8 weeks ago)

D       Blog_0421_Metrics.jpg

41e1be1 "Add files via upload"
Author: Matthew Stone <junkmail@sandboxstudio.net>
Date:   Thu Apr 8 19:03:18 2021 -0500 (8 weeks ago)

A       Blog_0421_Metrics.jpg
```

In the 'bssw.io' repo we see:

```
$ git log-short --name-status HEAD --not f51c5c7e -- images/Blog_0421_Metrics.jpg
10e0a812 "Copy Blog0421_Metrics.jpg from separate images repo into bssw.io/images"
Author: David E. Bernholdt <bernholdtde@ornl.gov>
Date:   Mon Apr 19 15:17:21 2021 -0400 (6 weeks ago)

A       images/Blog_0421_Metrics.jpg
```

So it looks like @bernholdt just copied that file over.  Therefore, the diff should be identical, right?

```
$ gitdist remote -v | grep "\(Git Repo\|^github.*fetch\)"
*** Base Git Repo: bssw.io
github  git@github.com:betterscientificsoftware/bssw.io.git (fetch)
*** Git Repo: bssw-images
github  git@github.com:betterscientificsoftware/images.git (fetch)

$ diff images/Blog_0421_Metrics.jpg bssw-images/Blog_0421_Metrics.jpg
[empty]
```

so that file 'Blog_0421_Metrics.jpg' is already taken care of.

So I will just copy over the other two files:

```
$ cd bssw-images/

$ cp 2021-04-SWMetricsInResearch-hero.png  KanbanAndScrumMakingTheBestOfBoth.png \
  ../images/

$ cd ..

$ git add images/

$ git status
On branch 738-update-image-refs-2
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   images/2021-04-SWMetricsInResearch-hero.png
        new file:   images/KanbanAndScrumMakingTheBestOfBoth.png

$ git commit -a -m "Copy over missing images from 'images' repo (#738)"
```

Now I am ready to run the conversion of the `*.md` files:

```
$ cd bssw.io/

$ time ./utils/convert_images_ref_to_rel_path_all.sh \
  &> convert_images_ref_to_rel_path_all.out

real    0m52.092s
user    0m8.868s
sys     0m32.292s

$ git status | grep "modified:" | wc -l
107

$ git commit -a
```

</details>

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
manually ...**
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [x] ***[EB Mem]*** Leave comment @mentioning a bssw.io site maintainer (**BSSw Maint**) asking to carry out final publication steps.
* [x] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [x] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by a bssw.io site maintainer (currently 'rinkug')

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: I had to manually merge this branch into 'preview' to fix some real and tricky merge conflicts in the commit 8d781e67f3d16e7d5522eb5109500f447d955851 that I pushed to 'preview'.  I then reran the sync GHA job and it passed.

I just triggered the rebuild of the preview.bssw.io site and it is running now.

**Comment by bartlettroscoe** [comment]
@bernhold, @curfman, @rinkug, @sbxchicago,

The transition of the images does not seem to be working.  Consider the transitioned file:

* https://github.com/betterscientificsoftware/bssw.io/blob/preview/CuratedContent/KanbanAndScrumMakingTheBestOfBoth.md
* https://github.com/betterscientificsoftware/bssw.io/blob/738-update-image-refs-2/CuratedContent/KanbanAndScrumMakingTheBestOfBoth.md

with the raw `*.md` shown at:

* https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/CuratedContent/KanbanAndScrumMakingTheBestOfBoth.md

showing the link:

```
[Example Kanban Board Cartoon from the book "Kanban and Scrum"]<img src='../images/KanbanAndScrumMakingTheBestOfBoth.png'/>
```

Now that relative image displays just fine at:

* https://github.com/betterscientificsoftware/bssw.io/blob/preview/CuratedContent/KanbanAndScrumMakingTheBestOfBoth.md

but it does not display on the rebuilt preview.bssw.io site:

* https://preview.bssw.io/items/kanban-and-scrum-making-the-best-of-both

But that image does display just fine when it was pointing to the separate images repo in:

* https://bssw.io/items/kanban-and-scrum-making-the-best-of-both

Any idea what the problem might be?

**Comment by bernhold** [comment]
The last build of the preview site failed.  Let me try to see if I can fix that and get a clean build before we declare defeat here.

**Comment by bartlettroscoe** [comment]
> The last build of the preview site failed. Let me try to see if I can fix that and get a clean build before we declare defeat here.

@bernhold, how can you tell?

**Comment by bernhold** [comment]
If it has been more than 10 min and the rebuild doesn't show that it has completed, it is considered failed.

**Comment by bernhold** [comment]
@bartlettroscoe I got a clean build and it looks like your test case and others I looked at are okay now.  More thorough checking is still needed, but I think the problem was elsewhere and the build process just didn't complete properly.

**Comment by bartlettroscoe** [comment]
>  I got a clean build and it looks like your test case and others I looked at are okay now

Okay, I can verify that:

* https://preview.bssw.io/items/kanban-and-scrum-making-the-best-of-both

is showing the image correctly now.

Now we just need someone (or some tool) to check all of these (or enough of them).  Seems like someone should invest some time in researching and getting a tool that will craw the preview.bssw.io and bssw.io sites and check all pages under those sites and verify that all of the links are valid.  Some ideas are given in:

* https://www.softwaretestinghelp.com/broken-link-checker/

This seems like a standard tool a web contractor would already have in hand.

NOTE: I have a Chrome plugin that will allow me to check links one page at a time but that is not scalable.

**Comment by bartlettroscoe** [comment]
I did some more spot checks for pairs of pages with images:

* https://preview.bssw.io/blog_posts/celebrating-apollo-s-50th-anniversary-when-100-flops-watt-was-a-giant-leap
  * Image: https://res.cloudinary.com/bssw/image/fetch/https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/images/Blog_0429_computer_600_318.png?raw=true
* https://github.com/betterscientificsoftware/bssw.io/blob/preview/Articles/Blog/ApolloGuidanceComputerPart1.md
  * Image: https://github.com/betterscientificsoftware/bssw.io/raw/preview/images/Blog_0429_computer_600_318.png

* https://preview.bssw.io/items/digging-deeper-into-agile-software-development
   * Image: https://res.cloudinary.com/bssw/image/fetch/w_200,h_200,c_fit/https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/images/AgileSoftwareDevelopmentMartin.jpg?raw=true
* https://github.com/betterscientificsoftware/bssw.io/blob/preview/CuratedContent/AgileSoftwareDevelopmentMartin.md
  * Image: https://github.com/betterscientificsoftware/bssw.io/raw/preview/images/AgileSoftwareDevelopmentMartin.jpg

* https://preview.bssw.io/pages/bssw-fellowship-program
  * Image: https://res.cloudinary.com/bssw/image/fetch/w_200,h_200,c_fit/https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/images/Logo_DOE_Unofficial_Sm.png?raw=true
* https://github.com/betterscientificsoftware/bssw.io/blob/preview/Site/BSSwFellowshipProgram/FellowshipsOverview.md
  * Image: https://github.com/betterscientificsoftware/bssw.io/raw/preview/images/Logo_DOE_Unofficial_Sm.png

In all of the above, the images seem to be displayed correctly on the preview.bssw.io site in these documents in these three different directories.  What is interesting about this is that the bssw.io site generator seems to be getting the images out on github even through they are actually on the local server from the local git repo.  (Not sure why it would not just serve the images directly from that server.)

Someone can do more spot checking but really a tool should be checking this to make sure the image links are correct.

**Comment by bartlettroscoe** [comment]
@bernhold, @prwolfe, other than for some more in comprehensive checking, I am not sure there is much more to be done with this PR than to merge it.  If there is a problem with some image is is likely not that hard to just fix it.

**Comment by bernhold** [comment]
Actually, I believe that all images within content are served through something called cloudinary, which I understand to be a specialized CDN (I think it will do automatic resizing).  A couple of the pages/images on your list had a directory GH URL instead of a cloudinary one.  But when I checked the HTML being served up from preview.bssw.io, they do indeed have the cloudinary "wrapper".

One of the reasons Parallactic (the front-end contractor) didn't want to serve directly from bssw.io was concerns about the potential bandwidth demands.  Cloudinary helps mitigate that.  As does using Github's bandwidth instead of our little server.

**Comment by rinkug** [comment]
> Someone can do more spot checking but really a tool should be checking this to make sure the image links are correct.

@bartlettroscoe: @karbarz could help sanity check. She is new to Git, so would need a strict sequence of steps to follow for the checking.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe: @karbarz could help sanity check. She is new to Git, so would need a strict sequence of steps to follow for the checking.

@rinkug, if someone wants to, they can look over some more articles with images on preview.bssw.io.  (There is no knowledge of Git needed.)  Otherwise, given what I saw and documented 10 days ago [above](https://github.com/betterscientificsoftware/bssw.io/pull/909#issuecomment-855292063), I think this PR is low-risk to merge.  Okay?

**Comment by rinkug** [comment]
> @rinkug, if someone wants to, they can look over some more articles with images on preview.bssw.io. (There is no knowledge of Git needed.) Otherwise, given what I saw and documented 10 days ago [above](https://github.com/betterscientificsoftware/bssw.io/pull/909#issuecomment-855292063), I think this PR is low-risk to merge. Okay?

Ok, lets merge this then.

**Comment by rinkug** [comment]
> @rinkug, if someone wants to, they can look over some more articles with images on preview.bssw.io. (There is no knowledge of Git needed.) Otherwise, given what I saw and documented 10 days ago [above](https://github.com/betterscientificsoftware/bssw.io/pull/909#issuecomment-855292063), I think this PR is low-risk to merge. Okay?

I looked at a few examples on preview and it looks fine. Will merge.

**Pull request merged**
