### PR TITLE
Testing expansion sections for different checklists

### PR DESCRIPTION
**Pull request by markcmiller86**
# Description

EB Member: @bartlettroscoe 

Am curious what you think of this approach to handling multiple checklists?

<details open>

<summary>Expand for checklist for bssw.io content</summary>

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [ ] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [ ] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [ ] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [ ] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Assign to one of the site maintainers to carry out final publication steps.
* [ ] ***[EB Mem]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[EB Mem]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[EB Mem]*** Verify new new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).

</details>

<details>

<summary>Expand for checklist for (internal) files</summary>

* [ ] Set list of Reviewers (at least one).
* [ ] Add to Project [BSSw Internal].
* [ ] View the modified `*.md` files as rendered in GitHub.
* [ ] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.
* [ ] Watch for PR check failures.
* [ ] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [ ] Ensure at least one reviewer signs off on the changes.
* [ ] Once reviewer has approved and PR check pass, then merge the PR.

</details>

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by markcmiller86** [comment]
One drawback is that GitHub counts *all* checklist items (not just those which are not-collapsed) in computing its `3 of 28` note in PR list view.

**Comment by bartlettroscoe** [comment]
@markcmiller86 

> Am curious what you think of this approach to handling multiple checklists?

That is interesting.  I like the idea of being able to expand and contract the checklist, even if there is just one checklist.

> One drawback is that GitHub counts all checklist items (not just those which are not-collapsed) in computing its 3 of 28 note in PR list view.

Right. Perhaps we should still recommend the PR author still delete the markdown for the checklist not used?

**Comment by bartlettroscoe** [comment]
## Proposal-2

How about the below checklist with expandable items and updated instructions?

The big differences with what is proposed [above](https://github.com/betterscientificsoftware/bssw.io/pull/808#issue-623561187) are:

* The instructions recommend deleting one of the two checklists
* The `<summary>` for the checklists are the bolded section headings followed by non-bold instructions "(Click to expand or contract)".

Opinions?

----

# Instructions (DELETE THIS SECTION)

To view these instructions, please hit the **Preview** tab (above left). After you have read all of these instructions, delete them entirely from the body of this issue before entering your submission.

Be sure to select `master` as the `base` branch above as the target for this PR.

Provide a general summary of your changes in the title above.

Fill in the below **Description** section with minimal text describing the changes/new contributions in this PR and replace `<...>` as appropriate.

Delete the Markdown for the checklist not being used for this PR and keep the other relevant checklist.  (The checklist items for *files displayed on the bssw.io site* are expanded by default.  The checklist items for *internal files not displayed in the bssw.io site** are contracted by default)

Any checklist items within the relevant checklist that don't apply can be striked out by adding `~~` to the beginning and end of the checklist item as `* ~~[] <checklist-item>~~`.  Also, remove the strikeout markers `~~` for the [wikize_refs.py] checklist items if using formal citations for bssw.io contributions.

# Description

EB Member: @`<eb-member-id>`

Addresses issue #`<issue-id>`

`<Other minimal information about the PR.>`


<details open>

<summary><b>PR checklist for files displayed on bssw.io site</b> (click to expand or contract)</summary>

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [ ] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [ ] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [ ] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [ ] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [ ] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [ ] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Assign to one of the site maintainers to carry out final publication steps.
* [ ] ***[EB Mem]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[EB Mem]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[EB Mem]*** Verify new new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
</details>





<details>

<summary><b>PR checklist for (internal) files not displayed on bssw.io site</b> (click to expand or contract)</summary>

* [ ] Set list of Reviewers (at least one).
* [ ] Add to Project [BSSw Internal].
* [ ] View the modified `*.md` files as rendered in GitHub.
* [ ] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.
* [ ] Watch for PR check failures.
* [ ] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [ ] Ensure at least one reviewer signs off on the changes.
* [ ] Once reviewer has approved and PR check pass, then merge the PR.

</details>



[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

**Comment by markcmiller86** [comment]
I was hoping to maybe replace the *delete this set of checklist items* stuff with expandable/collapsable stuff.

If we can't, I am not sure its worth it.

**Comment by bartlettroscoe** [comment]
> I was hoping to maybe replace the **delete this set of checklist items** stuff with expandable/collapsable stuff.
> 
> If we can't, I am not sure its worth it.

@markcmiller86, that is just a suggestion.  See the ***Suggestions*** list in the updated **Instructions** section in **Proposal-2** [above](https://github.com/betterscientificsoftware/bssw.io/pull/808#issuecomment-827061674).

I don't really feel too strongly one way to the other but I like the template in **Prospal-2** slightly better than the current PR template.  We should likely present these options at the next BSSw.io meeting (which I think is a process-based meeting).

**Comment by rinkug** [comment]
Can we discuss this in the call this week on thursday?

**Comment by markcmiller86** [comment]
> Can we discuss this in the call this week on thursday?

Sure thing.

**Comment by bartlettroscoe** [comment]
@bernhold, do you have an opinion if to go with [Proposal-2](https://github.com/betterscientificsoftware/bssw.io/pull/808#issuecomment-827061674) or what we currently have in [.github/PULL_REQUEST_TEMPLATE.md](ttps://github.com/betterscientificsoftware/bssw.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md)?  I prefer **Proposal-2** but i am okay with not changing.   @markcmiller86 prefers not to change.

**Comment by bernhold** [comment]
I do not have a particularly strong feeling either.

To me, templates are for other people to follow.  Bad attitude, I know, but the longer they are the less I like them.

That said, I am not sure that hiding is really a good solution.  Because the "wrong" checklist is still there and  it is easy to hide or unhide the wrong thing if you're not paying attention.  Also, if we ever get diligent about following the checklists, the progress indicators GH provides can have some value where they won't if we're just hiding them.

Also, does the hidden status persist across users, over time?  In two different comments, I just unhid the second checklist.  What does the next person (who isn't me) see?

**Comment by markcmiller86** [comment]
This was just testing an idea and I don't think it is highly favored so lets not spend more time on it.

**Pull request closed without merging**
