### PR TITLE
Article on Rubber Duck Debugging

### PR DESCRIPTION
**Pull request by bernhold**
Addresses #654

# Description

EB Member: @pagrubel

Addresses issue #654

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Assign to one of the site maintainers to carry out final publication steps.
* [ ] ***[EB Mem]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[EB Mem]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[EB Mem]*** Verify new new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Review by pagrubel — APPROVED** [review]
Looks good to me, links work.

**Comment by bartlettroscoe** [comment]
@bernhold, @rinkug 

FYI: I looked at this merge failure and I don't get a merge failure when I merge this branch into 'preview' locally.  But it looks like 'master' has not been merged to 'preview' for some reason.  The GitHub action that performs this is failing recently.  The most recent failure is shown in:

* https://github.com/betterscientificsoftware/bssw.io/runs/2551798786?check_suite_focus=true

It says it is a merge conflict error (but with no detail as to why the merge is failing as usual).   But I tried the merge of 'master' to 'preview' locally and it worked fine.  (I will push it.)

There is something really wrong with this GitHub Actions.  This just does not make sense.

**Comment by bartlettroscoe** [comment]
FYI: I manually merged this branch to the 'preview' branch so it can now be viewed on a rebuilt preview.bssw.io site.

**Comment by rinkug** [comment]
@pagrubel : The table needs the correct table headings, row headings etc..Could you pls check it against the style guide?

**Comment by pagrubel** [comment]
> @pagrubel : The table needs the correct table headings, row headings etc..Could you pls check it against the style guide?

Yes I will

**Review by pagrubel — CHANGES_REQUESTED** [review]
@bernhold The resource deck needs revision. After reading the style guid I suggest putting the book at the top with proper rows and columns and the other two resources at the bottom, changing the text a bit to match. Also, the site that the book resource links to is a place to buy the book. From the guide we aren't suppose to do that but I'm not sure what else to do (atleast it isn't the big A). I can make the changes for the format if you would like, just let me know

**Comment by bernhold** [comment]
@pagrubel I don't understand your suggestions. I'd like to talk through them.  Maybe we can connect for a few minutes at the end of today's EB meeting?  Or do we need to set another time?

**Comment by bernhold** [comment]
@pagrubel maybe we can spend a few minutes on this at Thursday's EB meeting.  It will be content-focused, so we should be able to breakout for a few minutes.

**Comment by pagrubel** [comment]
> @pagrubel maybe we can spend a few minutes on this at Thursday's EB meeting. It will be content-focused, so we should be able to breakout for a few minutes.

Sounds like a plan

**Comment by bernhold** [comment]
@pagrubel I think I've addressed your suggestions. Please re-review and let me know.  Thanks

**Comment by pagrubel** [comment]
@rinkug This is ready to publish.

**Review by pagrubel — APPROVED** [review]

**Pull request merged**
