### PR TITLE
Add topic 'Peer Code Review' (#777)

### LINKED ISSUE #777: Add subcategory "Peer Code Review" to bssw.io
CC: @betterscientificsoftware/bssw-editorial-board 

## Description

This Issue is to suggest/request adding the subcategory "Peer Review" under the major category  "Better Reliability" on the [bssw.io] site.

The current [bssw.io] site has several categories and subcategories.  One major subcategory that is missing is for "Peer Review".  As described in Chapter 20 "The Software-Quality Landscape" in  [Code Complete 2nd Edition], the two major tools for software quality assurance are reviews and testing.  While there are two subcategories for "testing" under the "Better Reliability" category, the work "review" does not appear in that category or any other subcategory.

Note that there are already several articles published on the bssw.io site that fall under this "Peer Review" subcategory (which can be found under the Google searches `site:bssw.io "Peer Review"` and `cite:bssw.io "Code Review"`) to initially populate this subcategory.

[bssw.io]: https://bssw.io
[Code Complete 2nd Edition]: https://bssw.io/items/code-complete-a-practical-handbook-of-software-construction

## Tasks:

* [ ] Add support for the subtopic "Peer code review" under "Better Reliability" on bssw.io (@rinkug)
* [ ] Add the subtopic "Peer code review" to the current bssw.io articles identified below (@bartlettroscoe)
* [ ] Update EB docs to define the "Peer code review" subtopic (@bartlettroscoe)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @`<eb-member-id>`

Resolves #777

## PR checklist for files displayed on bssw.io site

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [ ] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [ ] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]). **Added to [BSSw Internal]instead**
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [ ] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bernhold** [comment]
@bartlettroscoe please point me to the instructions you followed?

**Comment by bernhold** [comment]
@bartlettroscoe the problem is that you changed Site/Categories rather than Site/Topics.  I had the same problem last week.  Turns out we no longer use Site/Categories (just got confirmation today).  We should probably remove it from the repo.  Sorry about that.

The format of the Site/Topics files is very similar and should be obvious once you're in there.  But note that here there are no colons at the end of the topic.  Might save you a commit.

**Comment by bartlettroscoe** [comment]
> Turns out we no longer use Site/Categories (just got confirmation today). We should probably remove it from the repo. Sorry about that.

@bernhold, I will go ahead and delete it as part of this PR.

**Comment by bartlettroscoe** [comment]
Now that I correctly modified Site/Topics/Reliability.md and rebuilt the preview.bsswio site, we now see the new "Peer Code Review" category at:

* https://preview.bssw.io/

I will go ahead and merge.

**Pull request merged**
