### PR TITLE
DO NOT MERGE: Trial application of convert_images_ref_to_rel_path_all.sh (#738)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
I just ran:

```
$ time ./utils/convert_images_ref_to_rel_path_all.sh &> convert_images_ref_to_rel_path_all.out

real    0m42.594s
user    0m7.964s
sys     0m25.009s

$ grep "With line" convert_images_ref_to_rel_path_all.out | wc -l
202
```

on the 'master' branch on my Windows 10 laptop under cygwin and this is what it produced.

### CODE REVIEW

**Comment by bernhold** [comment]
@bartlettroscoe I converted this to draft to help protect against merging until we're ready.  If you don't like that, you can of course reverse it.

**Comment by bartlettroscoe** [comment]
>  converted this to draft to help protect against merging until we're ready. If you don't like that, you can of course reverse it.

@bernhold, that is fine.  This is really just a throw-away PR since it was generated with latterly a single command.

**Comment by rinkug** [comment]
@bartlettroscoe:  Hold off on any merges with this. We are still sorting stuff with vendor on this.

**Comment by bartlettroscoe** [comment]
Closing so we get this so it does not waste people's attention.   A new PR will get created once we are ready to actually make the transition (after the bssw.io site gets fixed).

**Pull request closed without merging**
