### PR TITLE
Adding CC for INI

### PR DESCRIPTION
**Pull request by markcmiller86**
# Description

EB Member: @rinkug 

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [ ] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [x] ***[EB Mem]*** Leave comment @mentioning a bssw.io site maintainer (**BSSw Maint**) asking to carry out final publication steps.
* [x] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [x] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by a bssw.io site maintainer (currently 'rinkug')

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by markcmiller86** [comment]
Hey @pagrubel sorry for any pressure. Will you have a chance to review this week? If not, I can re-assign. Lemme know. Thx.

**Comment by markcmiller86** [comment]
Is there anyone that has time to review this?

**Review by bernhold — APPROVED** [review]
LGTM, thanks

**Comment by markcmiller86** [comment]
@betterscientificsoftware/bssw-io-team this is ready to publish

@bartlettroscoe instructions say to @mention `bssw-maint` but I don't see that here.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe instructions say to @mention bssw-maint but I don't see that here.

@markcmiller86, the [above](https://github.com/betterscientificsoftware/bssw.io/pull/911#issue-662314548) says:

> Checklist items prefixed with ***[BSSw Maint]*** must be performed by a bssw.io site maintainer (currently 'rinkug')

**Comment by markcmiller86** [comment]
Hmm...would it make sense to have a *group* named `bssw-maint` populated by the (maybe one and only) people who have maintenance responsibilities?

**Comment by bernhold** [comment]
> Hmm...would it make sense to have a _group_ named `bssw-maint` populated by the (maybe one and only) people who have maintenance responsibilities?

I think it would.  Though what would be really useful is if you could *assign* an issue (PR) to a team.

**Comment by markcmiller86** [comment]
> Though what would be really useful is if you could _assign_ an issue (PR) to a team.

Looks like that has been a long outstanding request, https://github.com/dear-github/dear-github/issues/170

**Comment by rinkug** [comment]
https://bssw.io/items/the-inclusive-naming-initiative

**Review by rinkug — COMMENTED** [review]
LGTM

**Comment by rinkug** [comment]
https://bssw.io/items/the-inclusive-naming-initiative

**Pull request merged**
