### PR TITLE
Blog on 2021 BSSw.io community BOF

### PR DESCRIPTION
**Pull request by rinkug**
Author: @rinkug @mantrala-ops

EB Member: @bernhold 

Addresses issue #891 

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: preview`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Change meta-data to `Publish: yes` and commit if fully ready to publish.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment @mentioning a bssw.io site maintainer (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new new contribution shows up on [bssw.io] as expected.

### CODE REVIEW

**Comment by rinkug** [comment]
* Need to change hero image
* Need to get content checked
* Need to create figshare for talks

**Comment by rinkug** [comment]
@bartlettroscoe @bernhold : I rebuild preview but this article did not show up...

**Comment by bernhold** [comment]
Looks like there is a space is the filename.  I wouldn't be surprised if that's the source of the problem.  @rinkug, can you fix that please and check the preview again?

**Comment by bernhold** [comment]
Once this is confirmed, we need to flag this as something for PC to address.  It should work right or generate an error.

**Comment by rinkug** [comment]
Preview: https://preview.bssw.io/blog_posts/experiences-from-the-2021-bssw-io-community-bof

**Comment by bernhold** [comment]
We've had a couple of other interview-style blogs in the past.  They format things in a way I like.  The interviewer is named, and it is presented in a conversational style.  My suggestion would be to use as the interviewer someone who wasn't able to participate in the BOF.  But it could be anyone.

Would you consider changing to this format?

Interview-style blog examples: 
* <https://bssw.io/blog_posts/working-remotely-the-spack-team>
* <https://bssw.io/blog_posts/working-remotely-the-exascale-computing-project-ecp-panel-series>

**Comment by rinkug** [comment]
> We've had a couple of other interview-style blogs in the past. They format things in a way I like. The interviewer is named, and it is presented in a conversational style. My suggestion would be to use as the interviewer someone who wasn't able to participate in the BOF. But it could be anyone.
> 
> Would you consider changing to this format?
> 
> Interview-style blog examples:
> 
> * https://bssw.io/blog_posts/working-remotely-the-spack-team
> * https://bssw.io/blog_posts/working-remotely-the-exascale-computing-project-ecp-panel-series



> We've had a couple of other interview-style blogs in the past. They format things in a way I like. The interviewer is named, and it is presented in a conversational style. My suggestion would be to use as the interviewer someone who wasn't able to participate in the BOF. But it could be anyone.
> 
> Would you consider changing to this format?
> 
> Interview-style blog examples:
> 
> https://bssw.io/blog_posts/working-remotely-the-spack-team
> https://bssw.io/blog_posts/working-remotely-the-exascale-computing-project-ecp-panel-series

@bernhold : I have made the edits. Please check.

**Comment by bernhold** [comment]
@rinkug gave you a PR to match the style of the preview interview blogs.

**Comment by rinkug** [comment]
@karbarz :  Could you please review this article?

**Pull request merged**
