### PR TITLE
Tools needed to convert images to local repo refs (#703, #738)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @bernhold, @prwolfe

Addresses #703, #738

These are the scripts needed to convert the bssw.io repo references from the external github images repo to the local directory reference.  To run this for the entire repo, just checkout this branch and run:

```
$ cd bssw.io/
$ ./utils/convert_images_ref_to_rel_path_all.sh
``` 

I ran this on the entire bssw.io repo on 'master' as:

```
$ time ./utils/convert_images_ref_to_rel_path_all.sh &> convert_images_ref_to_rel_path_all.out.txt

real    0m41.297s
user    0m7.258s
sys     0m24.750s
```

(on my slow Cygwin Windows 10 machine) and it produced the output [convert_images_ref_to_rel_path_all.out.txt](https://github.com/betterscientificsoftware/bssw.io/files/6201492/convert_images_ref_to_rel_path_all.out.txt) and the changed files shown by:

```
$ git status | grep "modified:" &> git_status_modified_files.txt
```

showing the output [git_status_modified_files.txt](https://github.com/betterscientificsoftware/bssw.io/files/6201495/git_status_modified_files.txt).

You can see what the updated files looks like in PR https://github.com/bartlettroscoe/bssw.io/pull/4 with files shown at:

* https://github.com/bartlettroscoe/bssw.io/tree/703-convert-images-trial/

For example, you can see that GitHub is displaying the images correctly for the article:

* https://github.com/bartlettroscoe/bssw.io/blob/703-convert-images-trial/Articles/Blog/ApolloGuidanceComputerPart1.md

which has several images.

Here are the files that are not converted by this script:

```
$ find . -name "*.md" -exec grep -l "github[.]com/betterscientificsoftware/images/" {} \;
./docs/pages/bssw/bssw_content_highlighting.md
./docs/pages/bssw/bssw_pr_preview_branch.md
./docs/pages/bssw/bssw_styling_common.md
./docs/pages/bssw/bssw_styling_curated.md
./docs/pages/bssw/bssw_styling_originalarticles.md
./images/README.md
```

Someone needs to update the file `images/README.md` to make sense (see PR #754).

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@bernhold, @prwolfe, as noted in the comments starting in https://github.com/betterscientificsoftware/bssw.io/issues/738#issuecomment-806935811, it seems this converter could just use a simple repository absolute reference like `/images/<file-name>` instead of the relative references this tool puts in and it would work with GitHub.  What is not clear if that will work with other (local) Markdown editors/renderers or the web contractor's conversion software.

So what do we do here?  Do we leave this conversion software as is and use relative references like `.../../images/<file-name>` or do we change to use the (simpler to maintain) absolute repository references like `/images/<file-name>`?  It is not clear to me given my brief investigation of this starting in comment https://github.com/betterscientificsoftware/bssw.io/issues/738#issuecomment-806935811.

**Comment by bartlettroscoe** [comment]
We discussed this in the BSSW EB meeting today and @bernhold agreed that it is better to use the relative path `../../images/<file-name>` instead of the absolute path `/images/<file-name>` because the latter does not work with some local Markdown editors like MS Visual Studio.  Therefore, we should keep the translation tool as is in this PR.

So we just need a review and merge.

**Review by bernhold — APPROVED** [review]
LGTM, thanks

**Comment by bartlettroscoe** [comment]
> LGTM, thanks

Thanks @bernhold, I will go ahead and merge.

**Comment by bartlettroscoe** [comment]
@bernhold, here is the merged PR with the scripts that can do the auto-translation of the images.

**Pull request merged**
