### PR TITLE
Create ColorOracleTool.md

### LINKED ISSUE #793: Collect list of tools for assessing interface behavior in presence of impairments
This tool, https://colororacle.org/usage.html, is designed to allow non-impaired viewers to see what an interface looks like under various impaired (color) vision scenarios. I am guessing but there are probably other such tools on line to help developers ensure their software does a good job accomodating the needs of various user communiites (left handed, impaired vision or sound, dyslexia) etc. and gather a set of links into a CC here.

This is broadly under the heading of inclusive practices.

### PR DESCRIPTION
**Pull request by haikudeb**
# Description

Author:@haikudeb
EB Member: @rinkug

Resolves #793

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** @haikudeb the BSSw.io editorial board member @rinkug in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the issue-id in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

### CODE REVIEW

**Comment by rinkug** [comment]
@haikudeb : I made a few changes. Please approve is ok or revert if not ok.

**Comment by rinkug** [comment]
@markcmiller86 : Do you have time to do a quick review of this? Thank you

**Comment by markcmiller86** [comment]
@haikudeb apologies for [this commit[(https://github.com/haikudeb/deb_bssw.io/commit/f4c5a77762da5885bd5ed00d5515bff130e2d4fe) direct to your master branch. I tried a PR and it wouldn't allow it.

Please feel free to ignore my proposed changes (which are already committed to your master branch). You can do that by reverting the commit or just putting another commit that returns the file to its prior state.

Everything looked fine to me but I had some minor re-words and to adjust to one sentence per line. Even though women experience CVD at 0.5%, I worried mentioning only males suggested a bias we were not really trying to suggest.

**Comment by haikudeb** [comment]
Thanks Mark ! Good catch on the 0.5Sent from my iPhoneOn Oct 4, 2023, at 1:10 AM, markcmiller86 ***@***.***> wrote:﻿
@haikudeb apologies for [this commit[(https://github.com/haikudeb/deb_bssw.io/commit/f4c5a77762da5885bd5ed00d5515bff130e2d4fe) direct to your master branch. I tried a PR and it wouldn't allow it.
Please feel free to ignore my proposed changes (which are already committed to your master branch). You can do that by reverting the commit or just putting another commit that returns the file to its prior state.
Everything looked fine to me but I had some minor re-words and to adjust to one sentence per line. Even though women experience CVD at 0.5%, I worried mentioning only males suggested a bias we were not really trying to suggest.

**Comment by haikudeb** [comment]
Changes are good

**Pull request merged**
