### PR TITLE
CC: Update and transtion "Git Tutorial and Reference Collection" to bssw.io site article (#1283)

### LINKED ISSUE #1283: Update and transtion "Git Tutorial and Reference Collection" to bssw.io site article
@betterscientificsoftware/bssw-editorial-board,

I would like to upgrade and transition the "Git Tutorial and Reference Collection" page that I wrote years ago for the old IDEAS project at:

* https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/

to an original article on bssw.io.  Some of the links are stale and this really should be on bssw.io.

NOTE: I already transitioned the "Critical Beginner Git Usage Tips" page:

* http://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/beginner-tips/

to

* https://bssw.io/items/critical-beginner-git-usage-tips

that is linked to on that the  ["Git Tutorial and Reference Collection" page](https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/) so this is just finishing that off.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @rinkug 

Resolves #1283

This PR copies and updates the material on the page:

* https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/

to a native BSSw.io article.

What I did:

* Changed link to critical beginner git usage tips to the bssw.io article
* Removed links to some pages that were no longer valid
* Cleaned up and improved some of the text
* Did a good bit of web searching for more recent updates but did not really find too much and not anything better (IMHO)

NOTE: Even though there is a good bit of text in this updated `*.md` file its main purpose is to point to other material so I kept it as a curated content article.

After this PR merges I will:

* Gut https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/ and https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/beginner-tips/ and make them point to the bssw.io articles.

## PR checklist for files displayed on bssw.io site

* [ ] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* [x] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [x] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [ ] ***[Author]*** Make any final changes to the PR based on feedback.
* [ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).
* [ ] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [ ] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [ ] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

**Post-Merge Follow-up:**

* [x] Gut https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/beginner-tips/ and have it point to https://bssw.io/items/critical-beginner-git-usage-tips.
* [ ] Gut https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/ and have it point to https://preview.bssw.io/items/a-tutorial-and-reference-collection-for-git

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board,

Can one of you do a quick look over of this updated page?

I would like to get at least an initial version published before Tuesday morning, April 26.  I will be using this material in an internal seminar that I am giving on April 26 and I want to use this to drive people to the BSSw.io site instead of the old IDEAS site:

* https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/beginner-tips/

We can make any final edits and modifications based on feedback after April 26 but I want to make sure and get an initial version posted before that.

**Comment by bartlettroscoe** [comment]
I looked at the article on the generated site at:

* https://preview.bssw.io/items/a-tutorial-and-reference-collection-for-git

The topics look correct as well.

I think this is ready to publish but I would like at least one person to read it over carefully.

**Comment by rinkug** [comment]
@bartlettroscoe This is a good comprehensive summary. It does not follow the structure of using tables for CC. I liked the flow of it without the tables (so I didnt add the tables) - something for us to discuss later. I modified the language a bit.

@karbarz : can you review this for grammar on monday.
@curfman and @bartlettroscoe: If all looks good, then we can merge it and publish it tomm.

**Comment by bartlettroscoe** [comment]
@rinkug, thanks for the review.  I would like to get it published later today, even if it needs a few tweaks so I can use it in my presentation tomorrow.

**Pull request merged**
