### PR TITLE
Remove tests/ directory (#751)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This looks like an attempt to get the SNL auto-tester hooked up to the bssw.io GitHub repo to test PRs that got abandoned 3 years ago.  Makes sense to clean this up.  (This will still be in the git history if needed.)

See discussion in #751

Related to my epic SEPW-211

### CODE REVIEW

**Comment by JeanShuler** [comment]
This looks fine.

**Comment by bartlettroscoe** [comment]
> This looks fine.

@JeanShuler, thanks!  Can you officially approve the PR?  Just click on "Files Changed" above and them "Review  Changes" and check to box "Approve" with your comment and then click "Submit review".  That is how GitHub records and unambiguous review and approval for a PR.

**Comment by bartlettroscoe** [comment]
@william76, can you confirm this `tests/` directory is not longer needed and can be removed?  You added this directory and these files 3+ years ago.

**Comment by rinkug** [comment]
This is not being used and cannot be retrieved from history, if needed. Approving PR

**Comment by william76** [comment]
> @william76, can you confirm this `tests/` directory is not longer needed and can be removed? You added this directory and these files 3+ years ago.

@bartlettroscoe  

/shrug I don't remember what that was for, I haven't really been involved with this stuff in a few years.  I'd have to dig in and see if it matters, but it probably doesn't matter.  I see this got merged so if it didn't break anything then it's probably ok ;)

**Pull request merged**
