### PR TITLE
Event for SIAM CSE21

### PR DESCRIPTION
**Pull request by bernhold**

### CODE REVIEW

**Comment by rinkug** [comment]
We need some more text in the event for the main body section.
List of contributors is too long and will likely mess up the deck.

**Review by rinkug — CHANGES_REQUESTED** [review]
We need some more text in the event for the main body section.
List of contributors is too long and will likely mess up the deck.

**Comment by bernhold** [comment]
I feel that it says enough, so I don't know what more to add. @rinkug if you have thoughts on what additional text is needed, please feel free to add it to the PR.

**Review by rinkug — APPROVED** [review]

**Comment by rinkug** [comment]
> I feel that it says enough, so I don't know what more to add. @rinkug if you have thoughts on what additional text is needed, please feel free to add it to the PR.

I have added a brief description. Good to go from my side. 

@karbarz : Please ensure its consistent with style guide

**Comment by bernhold** [comment]
Just to reiterate, my first concern here is to make sure we have all of the sessions listed that should be here.  I went through the notes we had, but wanted other eyes to try to ensure I didn't miss something.  Thanks

**Comment by rinkug** [comment]
Perhaps the following?
* https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70066
* https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=69992
* https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=69993
* https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70202
* Maybe https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=71877 and its series?

**Comment by hnamLANL** [comment]
Nasir and Cindy are not listed in the author list.
I thought Mary Ann and Damian had a BE minisymposium also, but I have not been able to find it.

**Comment by rinkug** [comment]
> minisymposium

@hnamLANL : You mean the following?
https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70196
https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70224

**Comment by bernhold** [comment]
@hnamLANL the proposed contributors are the *organizers* of the sessions, not all of the actual speakers.  We already have too many organizers to be reasonable.

**Comment by rinkug** [comment]
> Nasir and Cindy are not listed in the author list.
> I thought Mary Ann and Damian had a BE minisymposium also, but I have not been able to find it.

@hnamLANL : You mean the following?
https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70196
https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70224

**Comment by hnamLANL** [comment]
The one for Damian (associated with BSSw Fellowship work) is 
https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=70303 

Mary Ann gave me the full BE schedule - do we want to include any of that since she's the organizer?
[BE Schedule 1_28_21.pdf](https://github.com/betterscientificsoftware/bssw.io/files/5906028/BE.Schedule.1_28_21.pdf)

**Comment by bernhold** [comment]
MS298 Wash Your Hands, Wear a Mask, Keep the Bugs Out and PD1-PD2-PD3 are good catches.

As to the BE stuff I'm not so sure.  I thought those sessions targeted a select set of people (students) in the program.  And also the Technical Research portion of BE doesn't seem to have any particular "software" content.

My feeling is that just because they're associated with us doesn't *necessarily* mean that everything they organize belongs on our list of software-related sessions.  And I don't think we want to be advertising things that are not openly accessible (my understanding of BE).  But open to discussion

**Pull request merged**
