### PR TITLE
fix renumber off by one

### LINKED ISSUE #1093: Possible issue with wikize_refs.py -r 1 -i
CC: @markcmiller86 

There might be an issue with the `wikize_refs.py -r` option.  When I ran:

```
$ cd ~/Articles/ShortArticles/

$ ../../utils/wikize_refs.py -r 1 -i CodingConvensions.md
```

on the commit version of the file `CodingConvensions.md` in commit https://github.com/bartlettroscoe/bssw.io/commit/3015586c243dc58a9591829c0559c22688198388 on the branch [435-cc-coding-conventions](https://github.com/bartlettroscoe/bssw.io/blob/435-cc-coding-conventions/Articles/ShortArticles/CodingConvensions.md) which had the references stated at:

image

it gave the commit https://github.com/bartlettroscoe/bssw.io/commit/6fc0950b237193739d2a37cdb17236a56ef2fbdb which I pushed to the branch [435-cc-coding-conventions-wikize_refs-r-issue](https://github.com/bartlettroscoe/bssw.io/blob/435-cc-coding-conventions-wikize_refs-r-issue/Articles/ShortArticles/CodingConvensions.md) which produced the references starting with '2' instead of '1' as:

image

Should this not start with '1' instead of '2'?

### PR DESCRIPTION
**Pull request by markcmiller86**
# Description

Resolves #1093 and adds a test for it

## PR checklist for (internal) files not displayed on bssw.io site

*Click "Write" above and remove comment markers to see below checklist items*

* [x] Set list of Reviewers (at least one).
* [x] Add to Project [BSSw Internal].
* ~~[ ] View the modified `*.md` files as rendered in GitHub.~~
* ~~[ ] If changes are to the GitHub pages site under the `docs/` directory, consider viewing locally with Jekyll.~~
* [x] Watch for PR check failures.
* [x] Make any final changes to the PR based on feedback and review GitHub (and Jekyll) rendered files.
* [x] Ensure at least one reviewer signs off on the changes.
* [x] Once reviewer has approved and PR check pass, then merge the PR.

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Review by bartlettroscoe — COMMENTED** [review]
I ran this locally on this branch with:

```
$ cd bssw.io/utils/tests/

$ ../wikize_refs.py -r 1 -o test_renumber.wr.md test_renumber.md
```

and it showed:

```
$ diff test_renumber.md test_renumber.wr.md

13c13
< Coding conventions<sup>[ccw]</sup>, also know as *coding standards* or *coding guidelines*, generally falls into the following categories:
---
> Coding conventions<sup>[1]</sup>, also know as *coding standards* or *coding guidelines*, generally falls into the following categories:
28c28
< In *Code Complete: 2nd Edition*<sup>[cc2nd04]</sup>, McConnell cites a study and notes:
---
> In *Code Complete: 2nd Edition*<sup>[2]</sup>, McConnell cites a study and notes:
...
< [ccw]: https://en.wikipedia.org/wiki/Coding_conventions "Coding Conventions (Wikipedia)"
...
> [ccw-sfer-ezikiw]: https://en.wikipedia.org/wiki/Coding_conventions "Coding Conventions (Wikipedia)"
...
> [1]: #sfer-ezikiw-1 "Coding Conventions (Wikipedia)"
...
> * <a name="sfer-ezikiw-1"></a><sup>1</sup>[Coding Conventions (Wikipedia)](https://en.wikipedia.org/wiki/Coding_conventions)
```

which shows that the numbering seems start with 1 correctly so I think this is working better.

However, I ran the unit tests with:

```
$ cd bssw.io/utils/

$ ./run_tests.sh                                                                                                                                           
Version of bssw.io repo being tested:                                                                                                                                                                              
ad985452 "fix renumber off by one"                                                                                                                                                                                 
Author: miller86 <miller86@llnl.gov>                                                                                                                                                                               
Date:   Fri Aug 26 09:58:04 2022 -0700 (5 hours ago)                                                                                                                                                               
-- Configuring done                                                                                                                                                                                                
-- Generating done                                                                                                                                                                                                 
-- Build files have been written to: /home/rabartl/BSSW.base/bssw.io/utils/build_tests                                                                                                                             
Test project /home/rabartl/BSSW.base/bssw.io/utils/build_tests                                       
...
74% tests passed, 5 tests failed out of 19

Total Test time (real) =   8.68 sec

The following tests did not run:
          7 - wikize_refs_goodlinks (Disabled)
          8 - wikize_refs_badlinks1 (Disabled)
          9 - wikize_refs_badlinks2 (Disabled)

The following tests FAILED:
         14 - wikize_refs_smartquotes (Failed)
         15 - wikize_refs_smartquotes_warn (Failed)
         19 - wikize_refs_linkdef_databases (Failed)
         20 - wikize_refs_linkdef_databases_pure (Failed)
         21 - wikize_refs_two_column (Failed)
Errors while running CTest
Output from these tests are in: /home/rabartl/BSSW.base/bssw.io/utils/build_tests/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

@markcmiller86, are you seeing the same errors?

We really should set up a GitHub Action to run these tests if there are any changes under the utils/ directory.

**Comment by markcmiller86** [comment]
All those tests run fine for me.

**Comment by markcmiller86** [comment]
```
% make test
Running tests...
Test project /Users/miller86/ideas-ecp/bssw.io/utils/test_build
      Start  1: wikize_refs_help
 1/22 Test  #1: wikize_refs_help .............................   Passed    0.23 sec
      Start  2: wikize_refs_no_args_pass
 2/22 Test  #2: wikize_refs_no_args_pass .....................   Passed    0.14 sec
      Start  3: wikize_refs_alpha_labels
 3/22 Test  #3: wikize_refs_alpha_labels .....................   Passed    0.14 sec
      Start  4: wikize_refs_anywhere_linkdefs
 4/22 Test  #4: wikize_refs_anywhere_linkdefs ................   Passed    0.14 sec
      Start  5: wikize_refs_rerun
 5/22 Test  #5: wikize_refs_rerun ............................   Passed    0.12 sec
      Start  6: wikize_refs_rerun_after_adding_link
 6/22 Test  #6: wikize_refs_rerun_after_adding_link ..........   Passed    0.16 sec
      Start  7: wikize_refs_goodlinks
 7/22 Test  #7: wikize_refs_goodlinks ........................***Not Run (Disabled)   0.00 sec
      Start  8: wikize_refs_badlinks1
 8/22 Test  #8: wikize_refs_badlinks1 ........................***Not Run (Disabled)   0.00 sec
      Start  9: wikize_refs_badlinks2
 9/22 Test  #9: wikize_refs_badlinks2 ........................***Not Run (Disabled)   0.00 sec
      Start 10: wikize_refs_no_args_fail
10/22 Test #10: wikize_refs_no_args_fail .....................   Passed    0.12 sec
      Start 11: wikize_refs_unused_linkdefs
11/22 Test #11: wikize_refs_unused_linkdefs ..................   Passed    0.12 sec
      Start 12: wikize_refs_nonexistent_linkdef
12/22 Test #12: wikize_refs_nonexistent_linkdef ..............   Passed    0.12 sec
      Start 13: wikize_refs_too_many_footnotes
13/22 Test #13: wikize_refs_too_many_footnotes ...............   Passed    0.12 sec
      Start 14: wikize_refs_smartquotes
14/22 Test #14: wikize_refs_smartquotes ......................   Passed    0.13 sec
      Start 15: wikize_refs_smartquotes_warn
15/22 Test #15: wikize_refs_smartquotes_warn .................   Passed    0.13 sec
      Start 16: wikize_refs_in_place
16/22 Test #16: wikize_refs_in_place .........................   Passed    0.15 sec
      Start 17: wikize_refs_in_place_no_save_orig
17/22 Test #17: wikize_refs_in_place_no_save_orig ............   Passed    0.14 sec
      Start 18: wikize_refs_in_place_and_explicit_out_fail
18/22 Test #18: wikize_refs_in_place_and_explicit_out_fail ...   Passed    0.12 sec
      Start 19: wikize_refs_linkdef_databases
19/22 Test #19: wikize_refs_linkdef_databases ................   Passed    0.13 sec
      Start 20: wikize_refs_linkdef_databases_pure
20/22 Test #20: wikize_refs_linkdef_databases_pure ...........   Passed    0.13 sec
      Start 21: wikize_refs_two_column
21/22 Test #21: wikize_refs_two_column .......................   Passed    0.13 sec
      Start 22: wikize_refs_renumber
22/22 Test #22: wikize_refs_renumber .........................   Passed    0.14 sec

100% tests passed, 0 tests failed out of 19

Total Test time (real) =   2.66 sec

The following tests did not run:
	  7 - wikize_refs_goodlinks (Disabled)
	  8 - wikize_refs_badlinks1 (Disabled)
	  9 - wikize_refs_badlinks2 (Disabled)
% git branch
  master
* mcm86-26Aug22-fix-wr-renumber
  preview
% pwd
/Users/miller86/ideas-ecp/bssw.io/utils/test_build
```

**Comment by bartlettroscoe** [comment]
@markcmiller86, okay, let me try to dig into why these tests are failing on my machine.

**Comment by bartlettroscoe** [comment]
@markcmiller86, the problem is that wikize_refs.py does not seem to be printing the same STDOUT that it was before. For example, for the test `wikize_refs_smartquotes` the expected output should contain:

* "Replace smart/curly quotes in link definition at line 148 with straight quotes" 

but even when I ran that manually, it produces no STDOUT:

```
$ cd bssw.io/utils/build_tests/tests/wikize_refs_smartquotes/

$ which python
/usr/bin/python

$ python --version
Python 3.8.12

$ ../../../wikize_refs.py test_smartquotes.md
[empty]
```

But I checked out the previous version of the repo 8896daad:

```
8896daad "Merge pull request #1409 from betterscientificsoftware/sbxchicago-patch-4"
Author: Matthew Stone <junkmail@sandboxstudio.net>
Date:   Tue Aug 23 17:47:32 2022 -0500 (6 days ago)
```


and that version does not produce any STDOUT either.

So these failures don't seem to be related to the new commit in this PR.

**Review by bartlettroscoe — APPROVED** [review]
As the tests are passing for @markcmiller86 and they are still broken for me with what is on 'mastesr', let's go ahead this PR.  I can track down what is happening with these test failures as a separate issue.  We also need to put in a GitHub Actions check that runs the wikize-refs.py checks.  All you need is Python and CMake on any Linux-like machine to do that.

**Comment by markcmiller86** [comment]
@bartlettroscoe I can confirm that if I change sh-bang line in `wikize_refs.py` to invoke a `python3` instead, I also get failures. So, I am thinking `wikize_refs.py` isn't quite up to handling python 2 and python 3 correctly. 

I'll merge this and then correct python 2/3 issues in another PR.

**Pull request merged**
