### PR TITLE
CC: First draft of Google Guidance on Code Review (#1759)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
# Description

EB Member: @rinkug 

Resolves:

* #1759

Provides a short summary of the Google Code Review Developers Guide.   I added a bulleted list of some of the better suggestions from reading over the entire Google Code Review Developers Guide pages.

NOTE: I did **not** summarize the reference document [CL Author’s Guide](https://google.github.io/eng-practices/review/developer/) but that is worth reading as well.  (Just substitute "commit" for "CL" for you Git users.)

## PR checklist for files displayed on bssw.io site

* [x] ***[Author]*** `@mention` the BSSw.io editorial board member `@<eb-member-id>` in **Description** above assigned to shepherd your PR.
* [x] ***[Author]*** Add the `<issue-id>` in the **Description** above for the associated GitHub Issue.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py])~~.
* [x] ***[Author]*** Inspect the content in the `*.md` file(s) as rendered in GitHub for this PR.
* [x] ***[EB Mem]*** Assign this PR to the EB member `<eb-member-id>`.
* [x] ***[EB Mem]*** Assign this PR to the author of the PR `<pr-author-id>`.
* [ ] ***[EB Mem]*** Add one or more Reviewers.
* [x] ***[EB Mem]*** Add label `content: <content-type>` for the type of contribution.
* [x] ***[EB Mem]*** Add to Project `Content Development` (see [Content Development]).
* [x] ***[EB Mem]*** Add [meta-data] to the `*.md` file(s) (set `Publish: yes`).
* [x] ***[EB Mem]*** Add label `preview` (so PR branch will be merged to 'preview' branch and watch for possible merge failures).
* [x] ***[EB Mem]*** Rebuild [preview] site and confirm new content is there, renders correctly and is returned in searches.
* [x] ***[Author]*** Make any final changes to the PR based on feedback.
* ~~[ ] ***[Author]*** Ensure `wikize_refs.py -i <base>.md` is run and commit (if using [wikize_refs.py]).~~
* [x] ***[EB Mem]*** Rebuild [preview] site and re-confirm content looks correct.
* [x] ***[EB Mem]*** Ensure at least one reviewer signs off on the final changes.
* [x] ***[EB Mem]*** Move the PR to "Ready to Publish" in [Content Development].
* [ ] ***[EB Mem]*** Leave comment and @mention `@betterscientificsoftware/bssw-maint` (**BSSw Maint**) asking to carry out final publication steps.
* [ ] ***[BSSw Maint]*** Verify that all needed files are present in the PR (article, images, updates to Site/Homepage.md carousel and/or Site/Announcements/Announcements.md as appropriate).
* [ ] ***[BSSw Maint]*** Merge PR. (Should automatically move to "Done" in [Content Development].)
* [ ] ***[BSSw Maint]*** Verify new contribution shows up on [bssw.io] as expected.

NOTE:
* Checklist items prefixed with ***[Author]*** are expected to be performed by the author of the PR or can be performed by the author.
* Checklist items prefixed with ***[EB Mem]*** must be performed by a [BSSw.io Editorial Board (EB) Member](https://betterscientificsoftware.github.io/bssw.io/bssw_members.html).
* Checklist items prefixed with ***[BSSw Maint]*** must be performed by someone in the `@betterscientificsoftware/bssw-maint` team (hint: type `@`, `b`, `s`, `s`, `w`, `-`, `m`  to auto-complete to `@betterscientificsoftware/bssw-maint`).

[preview]: https://preview.bssw.io
[bssw.io]: https://bssw.io
[Content Development]: https://github.com/betterscientificsoftware/bssw.io/projects/3
[BSSw Internal]: https://github.com/betterscientificsoftware/bssw.io/projects/2
[meta-data]: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#metadata-section
[wikize_refs.py]: https://github.com/betterscientificsoftware/bssw.io/blob/master/utils/README.md#wikize_refspy

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Hello @betterscientificsoftware/bssw-editorial-board, does one of you have time to review this CC article for the August BSSw Digest?

**Comment by rinkug** [comment]
> Hello @betterscientificsoftware/bssw-editorial-board, does one of you have time to review this CC article for the August BSSw Digest?

I will take a look today or tomorrow?

**Comment by rinkug** [comment]
@bartlettroscoe 
> Some examples of the good guidance in this developer guide include (in which "Commit" has been substituted for "CL" in the Google Developers Guide):

This Commit/CL part is unclear. Rest looks great

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe
> 
> > Some examples of the good guidance in this developer guide include (in which "Commit" has been substituted for "CL" in the Google Developers Guide):
> 
> This Commit/CL part is unclear. Rest looks great

@rinkug, this is to remind readers of equivalence of a Perforce CL (Change list) and a Git Commit from the above sentence:

https://github.com/betterscientificsoftware/bssw.io/blob/fb4049496ad54111b7815e0c482e8ba40e10f39f/CuratedContent/GoogleGuidanceOnCodeReview.md?plain=1#L21

I will try to reword to try to better explain what I mean.

**Comment by bartlettroscoe** [comment]
@rinkug, hopefully the text in the new commit https://github.com/betterscientificsoftware/bssw.io/pull/1781/commits/06ce8b2186be6e351d83ada52f20d0353490e620 will be more clear about "CL" and "commit" and why I mention it and think it is important (for people familiar with Git but not Perforce).

**Review by rinkug — COMMENTED** [review]
LGTM

**Pull request merged**
