### PR TITLE
Create onboarding issue with checklist

### PR DESCRIPTION
**Pull request by markcmiller86**
Add issue template for onboarding new member

### CODE REVIEW

**Comment by markcmiller86** [comment]
@bartlettroscoe and @bernhold here is a new issue template. 

One thought...email address for google docs might require an additional note. My google email is not my work email and I of ten get stuff shared with me at work that I can't read/edit because they didn't share it to the right email.

**Comment by markcmiller86** [comment]
Also, I dunno if some of the actions in the checklist can be performed by only some of the members. But, I went to add keith to @betterscientificsoftware/bssw-editorial-board group and I could not find a way to do that either from org or bssw.io repo.

**Comment by rinkug** [comment]
LGTM

**Comment by rinkug** [comment]
@ksbeattie : @markcmiller86 is present on   @betterscientificsoftware/bssw-editorial-board group

**Pull request merged**
